/**
 * Shared day rows for multi-length Battle plans (battle10/14/21/30/40).
 * Loaded by plans.html before the inline script. Single source — edit wording here.
 *
 * Authoring new plans: see docs/BATTLE-PLAN-AUTHORING.md (markdown draft template + wiring checklist).
 */
(function (global) {
  'use strict';
  var core9 = [
{ title: 'Name the noise', ref: 'Matthew 6:33', text: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.',
  speaker: 'Jesus in the Sermon on the Mount', plain: 'Stop chasing the side things. Put God first and everything else lines up.', today: 'What are you scrolling toward instead of Him?', action: 'Set your phone face-down for 30 minutes and open the Word instead.', prayer: 'Lord, put You first today. Help me stop chasing what doesn\'t matter. Amen.' },
{ title: 'Guard the gate', ref: 'Philippians 4:8', text: 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.',
  speaker: 'Paul from prison — choosing his thoughts deliberately', plain: 'Your mind is a gate. You decide what gets in.', today: 'What content are you letting in that you wouldn\'t want God watching with you?', action: 'Unfollow or mute one account today that pulls you away from peace.', prayer: 'Father, guard my heart. Let me choose what gets in. Amen.' },
{ title: 'The enemy\'s tactic', ref: '1 Peter 5:8', text: 'Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour.',
  speaker: 'Peter to scattered believers under pressure', plain: 'Distraction isn\'t random. It\'s a strategy against you.', today: 'Where are you most distracted? That\'s likely where the attack is focused.', action: 'Name the distraction out loud. Then say: "I see you. I choose God."', prayer: 'God, I see the distraction. I choose You. Amen.' },
{ title: 'Renew the mind', ref: 'Romans 12:2', text: 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.',
  speaker: 'Paul calling believers to a different standard', plain: 'The world will shape you if you let it. Renewal is active, not passive.', today: 'What has the world\'s noise told you to believe this week?', action: 'Spend 5 minutes in Scripture before touching social media tomorrow morning.', prayer: 'Lord, renew my mind. Don\'t let the world shape me. Amen.' },
{ title: 'Stand firm', ref: 'Ephesians 6:13', text: 'Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all, to stand.',
  speaker: 'Paul — a prisoner writing about spiritual warfare', plain: 'You don\'t fight to win. You stand because God already won. Your job is to hold the ground.', today: 'What ground are you giving up through distraction?', action: 'Write down one boundary you will hold today. Keep it.', prayer: 'God, help me stand. I hold the ground You\'ve given. Amen.' },
{ title: 'Eyes on the prize', ref: 'Hebrews 12:1-2', text: 'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith.',
  speaker: 'The writer of Hebrews to a tired church', plain: 'Drop the weight. Stop looking sideways. Eyes on Jesus, keep running.', today: 'What weight — habit, app, person — slows your run?', action: 'Delete one app or break one habit that distracts you from the race.', prayer: 'Lord, eyes on Jesus. Drop the weight. Keep running. Amen.' },
{ title: 'The peace that guards', ref: 'Philippians 4:7', text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
  speaker: 'Paul — same letter, same prison, same peace', plain: 'God\'s peace doesn\'t make sense. It just shows up and stands guard anyway.', today: 'You\'ve battled distraction for 7 days. Where do you feel calmer?', action: 'Pray today: "Guard my heart and mind. Keep me focused on what matters." Then rest.', prayer: 'Father, guard my heart and mind. Keep me focused on what matters. Amen.' },
{ title: 'Keep thy heart', ref: 'Proverbs 4:23', text: 'Keep thy heart with all diligence; for out of it are the issues of life.',
  speaker: 'Solomon — father to son — on what matters most', plain: 'Everything flows from the heart. Guard it like your life depends on it. It does.', today: 'What is leaking out of your heart into your choices this week?', action: 'Pause before one decision today. Ask: "Is this from a guarded heart or a leaky one?"', prayer: 'Lord, keep my heart. Guard what flows out. Amen.' },
{ title: 'Cast down imaginations', ref: '2 Corinthians 10:5', text: 'Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ.',
  speaker: 'Paul — defending his ministry, teaching spiritual warfare', plain: 'Thoughts that oppose God don\'t get a free pass. Capture them. Bring them to Christ.', today: 'What thought has been running loose that needs to be brought captive?', action: 'Name one thought. Say: "I bring this to the obedience of Christ." Then release it.', prayer: 'Lord, I bring every thought captive to You. Amen.' },
  ];
  var post4 = [
{ title: 'Set affection above', ref: 'Colossians 3:2', text: 'Set your affection on things above, not on things on the earth.',
  speaker: 'Paul — redirecting the Colossians\' focus', plain: 'Affection follows where you set it. Choose above.', today: 'Where is your affection set — on things above or things on earth?', action: 'Before opening any app today, ask: "Is this above or below?" Choose one thing above.', prayer: 'Lord, set my affection on things above. Amen.' },
{ title: 'No man that warreth', ref: '2 Timothy 2:4', text: 'No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier.',
  speaker: 'Paul to Timothy — a young pastor in the fight', plain: 'Soldiers don\'t get tangled in civilian affairs. You\'re at war. Stay untangled.', today: 'What affair of this life has you entangled right now?', action: 'Name one entanglement. Pray: "I lay this down. I please You, not it."', prayer: 'Lord, I stay untangled. I please You. Amen.' },
{ title: 'One thing is needful', ref: 'Luke 10:41-42', text: 'And Jesus answered and said unto her, Martha, Martha, thou art careful and troubled about many things: But one thing is needful: and Mary hath chosen that good part, which shall not be taken away from her.',
  speaker: 'Jesus — at Martha\'s house — redirecting her focus', plain: 'Many things clamor. One thing is needful. Choose it.', today: 'What "many things" are you troubled about that aren\'t the one needful thing?', action: 'Sit with the Word for 10 minutes today. That\'s the good part. Choose it.', prayer: 'Lord, I choose the one needful thing. Amen.' },
{ title: 'Love not the world', ref: '1 John 2:15', text: 'Love not the world, neither the things that are in the world. If any man love the world, the love of the Father is not in him.',
  speaker: 'John — to believers who knew the cost of compromise', plain: 'You can\'t love the world and the Father. One will win.', today: 'What from the world are you still loving that competes with the Father?', action: 'Name it. Then say: "I choose the Father over this." Mean it.', prayer: 'Father, I choose You over the world. Amen.' },
  ];
  var mid7 = [
{ title: 'Be stedfast', ref: '1 Corinthians 15:58', text: 'Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.',
  speaker: 'Paul — after the resurrection chapter — calling for steadfastness', plain: 'Steadfast. Unmoveable. Your labour isn\'t in vain.', today: 'Where have you been moveable when you should have stood?', action: 'Pick one area. Be unmoveable there today.', prayer: 'Lord, I am steadfast. My labour is not in vain. Amen.' },
{ title: 'Walk circumspectly', ref: 'Ephesians 5:15-16', text: 'See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil.',
  speaker: 'Paul — on how to walk in a dark age', plain: 'Redeem the time. The days are evil. Walk like you know it.', today: 'How did you spend your time yesterday? Redeemed or wasted?', action: 'Redeem one hour today. Use it for something that matters.', prayer: 'Lord, I redeem the time. Walk circumspectly. Amen.' },
{ title: 'Unite my heart', ref: 'Psalm 86:11', text: 'Teach me thy way, O LORD; I will walk in thy truth: unite my heart to fear thy name.',
  speaker: 'David — in a psalm of dependence', plain: 'A divided heart scatters. Ask Him to unite it.', today: 'Is your heart united toward God or scattered toward a hundred things?', action: 'Pray this verse. Then notice one way your heart is divided. Bring it to Him.', prayer: 'Lord, unite my heart to fear Your name. Amen.' },
{ title: 'Watch and be sober', ref: '1 Thessalonians 5:6', text: 'Therefore let us not sleep, as do others; but let us watch and be sober.',
  speaker: 'Paul — to a church waiting for the Lord', plain: 'Don\'t sleepwalk through life. Watch. Be sober.', today: 'Where are you sleepwalking — numb to what matters?', action: 'Wake up in one area today. Pay attention. Be present.', prayer: 'Lord, I watch and am sober. I do not sleep. Amen.' },
{ title: 'Run not uncertainly', ref: '1 Corinthians 9:26', text: 'I therefore so run, not as uncertainly; so fight I, not as one that beateth the air.',
  speaker: 'Paul — on his own discipline as an athlete', plain: 'Run with purpose. Fight with aim. No beating the air.', today: 'Are you running uncertainly or with clear purpose?', action: 'Name the race you\'re in. Then run one step with intention today.', prayer: 'Lord, I run not uncertainly. I fight with aim. Amen.' },
{ title: 'Number our days', ref: 'Psalm 90:12', text: 'So teach us to number our days, that we may apply our hearts unto wisdom.',
  speaker: 'Moses — in a psalm about the brevity of life', plain: 'Numbered days make wise hearts. Don\'t waste them.', today: 'How many of your days have you applied to wisdom this month?', action: 'Count: how many days this week did you spend time in the Word? Add one.', prayer: 'Lord, teach me to number my days. Apply my heart to wisdom. Amen.' },
{ title: 'Abstain from lusts', ref: '1 Peter 2:11', text: 'Dearly beloved, I beseech you as strangers and pilgrims, abstain from fleshly lusts, which war against the soul.',
  speaker: 'Peter — to exiles who knew the cost of compromise', plain: 'Fleshly lusts war against the soul. Abstain. You\'re a pilgrim, not a settler.', today: 'What fleshly lust is warring against your soul right now?', action: 'Name it. Abstain from it for today. One day at a time.', prayer: 'Lord, I abstain. I am a pilgrim. Amen.' },
  ];
  var tail8 = [
{ title: 'Meditate day and night', ref: 'Joshua 1:8', text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.',
  speaker: 'God to Joshua — at the start of the promised land', plain: 'The Word in your mouth. Day and night. That\'s the rhythm.', today: 'How often is the Word in your mouth — or only in your feed?', action: 'Speak one verse out loud today. Let it depart from your mouth into the air.', prayer: 'Lord, the Word does not depart from my mouth. Amen.' },
{ title: 'Commit thy works', ref: 'Proverbs 16:3', text: 'Commit thy works unto the LORD, and thy thoughts shall be established.',
  speaker: 'Solomon — on the connection between commitment and clarity', plain: 'Commit your works. Then your thoughts get established. Order follows surrender.', today: 'What works have you not committed to Him?', action: 'Commit one thing to the Lord today — out loud. Then watch your thoughts.', prayer: 'Lord, I commit my works to You. Establish my thoughts. Amen.' },
{ title: 'Draw nigh to God', ref: 'James 4:8', text: 'Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded.',
  speaker: 'James — direct and practical', plain: 'Draw nigh. He draws nigh. It\'s a two-way move.', today: 'When did you last draw nigh — not out of duty, but desire?', action: 'Draw nigh today. One step. He meets you.', prayer: 'Lord, I draw nigh. Draw nigh to me. Amen.' },
{ title: 'Pure in heart', ref: 'Matthew 5:8', text: 'Blessed are the pure in heart: for they shall see God.',
  speaker: 'Jesus in the Beatitudes', plain: 'Purity of heart isn\'t perfection. It\'s single-mindedness. The pure see God.', today: 'Is your heart pure — single toward Him — or divided?', action: 'Ask Him to purify your heart in one area today. Receive it.', prayer: 'Lord, purify my heart. I want to see You. Amen.' },
{ title: 'Fear God', ref: 'Ecclesiastes 12:13', text: 'Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man.',
  speaker: 'The Preacher — after trying everything under the sun', plain: 'The whole duty. Fear God. Keep His commandments. Everything else is vanity.', today: 'Is fearing God the conclusion of your matter, or an afterthought?', action: 'Make fearing God the first thing today. Before the scroll. Before the task.', prayer: 'Lord, I fear You. I keep Your commandments. This is my duty. Amen.' },
{ title: 'Grace teaches', ref: 'Titus 2:11-12', text: 'For the grace of God that bringeth salvation hath appeared to all men, Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world.',
  speaker: 'Paul to Titus — on what grace actually does', plain: 'Grace teaches. It doesn\'t excuse. It trains you to live soberly, righteously, godly.', today: 'Is grace teaching you — or are you using it as an excuse?', action: 'Let grace teach you one thing today. Deny one ungodly impulse.', prayer: 'Lord, Your grace teaches me. I live soberly, righteously, godly. Amen.' },
{ title: 'Iron sharpeneth iron', ref: 'Proverbs 27:17', text: 'Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.',
  speaker: 'Solomon — on the power of true friendship', plain: 'You need people who sharpen you. Not just affirm you. Sharpen.', today: 'Who sharpens you? Who do you sharpen?', action: 'Reach out to one person who sharpens you. Or become that for someone.', prayer: 'Lord, sharpen me through my friends. Let me sharpen others. Amen.' },
{ title: 'Already won', ref: '1 Corinthians 15:57', text: 'But thanks be to God, which giveth us the victory through our Lord Jesus Christ.',
  speaker: 'Paul after explaining the resurrection — the victory is the point', plain: 'You\'re not fighting for victory. You\'re fighting from it.', today: 'Start from victory, not toward it. The battle is already decided.', action: 'Face today\'s hardest thing from this place: "He already won this."', prayer: 'Thanks be to God. He already won. Amen.' },
  ];
  var cap10 = { title: '10 days in', ref: 'Psalm 119:105', text: 'Thy word is a lamp unto my feet, and a light unto my path.',
  speaker: 'The psalmist — after 176 verses on the Word', plain: 'You\'ve walked 10 days with the Word. It\'s lighting your path. Keep going.', today: 'Where has the Word lit your path this week?', action: 'Write down one way Scripture has guided you. Thank Him for it.', prayer: 'Lord, Your word is my lamp. Thank You for 10 days. Amen.' };
  var cap14 = { title: '14 days strong', ref: '1 Corinthians 15:58', text: 'Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.',
  speaker: 'Paul — after the resurrection chapter — calling for steadfastness', plain: 'Two weeks in. Be steadfast. Unmoveable. Your labour isn\'t in vain.', today: 'You\'ve held the line for 14 days. What has shifted?', action: 'Write down one way you\'re more steadfast than when you started. Thank Him.', prayer: 'Lord, I am steadfast. My labour is not in vain. Thank You for 14 days. Amen.' };
  var cap21 = { title: '21 days — habit formed', ref: 'Joshua 1:8', text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.',
  speaker: 'God to Joshua — at the start of the promised land', plain: 'Three weeks in. The habit is forming. Don\'t let the Word depart from your mouth.', today: 'You\'ve built 21 days. How will you keep the Word in your mouth?', action: 'Commit to one way you\'ll continue — a time, a place, a rhythm. Write it down.', prayer: 'Lord, the Word does not depart from my mouth. Thank You for 21 days. Amen.' };
  var cap30deep = { title: '30 days deep', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'Not a distant help. A very present one. Right here. Right now.', today: 'You made it 30 days. Look at the ground you\'ve held. It\'s real.', action: 'Write down three ways you\'ve cut through distraction. Offer them back to Him.', prayer: 'Lord, You are my refuge and strength. Thank You for 30 days. Amen.' };
  var cap30final = { title: '30 days deep', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'A full month in the Word changes you. You\'ve built something real.', today: 'Even on the hardest days, you now reach for truth first instead of noise.', action: 'Look back at your first day. See how far He\'s carried you. Thank Him out loud. Then write one sentence: "Because of these 30 days, I now..."', prayer: 'Lord, thank You for every verse, every hard day, every small win. Keep building in me what You started. Amen.' };
  var capWildernessBridge = { title: '30 days — into the wilderness', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'Not a distant help. A very present one. Right here. Right now.', today: 'You made it 30 days. The next 10 are the wilderness stretch—trust, provision, temptation.', action: 'Write down one way God has been your refuge. Carry it into the next 10 days.',   prayer: 'Lord, You are my refuge and strength. I enter the wilderness with You. Amen.' };
  var preCap30 = { title: 'Do not weary', ref: 'Galatians 6:9', text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.',
  speaker: 'Paul — closing his letter to churches worn down by opposition', plain: 'Weariness is not failure. "Faint not" is permission to rest in Him—and keep sowing.', today: 'Day 29: you are not behind. In due season you will reap if you do not give up.', action: 'Name one small "well doing" you can keep today without performing for anyone.', prayer: 'Lord, I am weary but I faint not in You. Sustain me to day 30. Amen.' };
  var wilderness10 = [
{ title: 'Man shall not live by bread alone', ref: 'Matthew 4:4', text: 'But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.',
  speaker: 'Jesus — in the wilderness, tempted by the devil', plain: 'In the wilderness, provision isn\'t just food. It\'s every word from God.', today: 'What are you living by — bread alone, or His Word?', action: 'Let one verse from God\'s mouth feed you today. Sit with it.', prayer: 'Lord, I live by every word from Your mouth. Not bread alone. Amen.' },
{ title: 'He shall give his angels charge', ref: 'Psalm 91:11', text: 'For he shall give his angels charge over thee, to keep thee in all thy ways.',
  speaker: 'The psalmist — to one who dwells in the secret place', plain: 'In the wilderness, you\'re not alone. Angels have charge over you.', today: 'Where do you need to remember you\'re kept?', action: 'Name one "way" you\'re walking. Pray: "Keep me in this way."', prayer: 'Lord, Your angels have charge over me. I am kept. Amen.' },
{ title: 'Trust in the LORD', ref: 'Proverbs 3:5-6', text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
  speaker: 'Solomon — father to son — on the core of wisdom', plain: 'Wilderness seasons strip away your own understanding. Trust replaces it.', today: 'Where are you leaning on your own understanding instead of Him?', action: 'Acknowledge Him in one decision today. Let Him direct.', prayer: 'Lord, I trust You with all my heart. Direct my paths. Amen.' },
{ title: 'Bread from heaven', ref: 'Exodus 16:4', text: 'Then said the LORD unto Moses, Behold, I will rain bread from heaven upon you; and the people shall go out and gather a certain rate every day; that I may prove them, whether they will walk in my law, or no.',
  speaker: 'God to Moses — in the wilderness, before the manna', plain: 'God provided daily. Not a stockpile. Daily. That\'s the wilderness rhythm.', today: 'Are you gathering today\'s portion, or hoarding yesterday\'s?', action: 'Receive today\'s portion from God. Don\'t reach for tomorrow\'s yet.', prayer: 'Lord, rain bread from heaven. I gather today\'s rate. Amen.' },
{ title: 'The LORD is my shepherd', ref: 'Psalm 23:1', text: 'The LORD is my shepherd; I shall not want.',
  speaker: 'David — the shepherd-king — who knew wilderness and green pastures', plain: 'In the wilderness, the Shepherd leads. You shall not want.', today: 'What do you want that the Shepherd hasn\'t provided?', action: 'Say: "I shall not want." Mean it. Rest in it.', prayer: 'Lord, You are my Shepherd. I shall not want. Amen.' },
{ title: 'Wait on the LORD', ref: 'Isaiah 40:31', text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
  speaker: 'Isaiah — to exiles in their own wilderness', plain: 'Waiting isn\'t passive. It renews. Eagles, running, walking—all from waiting.', today: 'Where are you running ahead instead of waiting?', action: 'Wait on the Lord in one area today. Let Him renew your strength.', prayer: 'Lord, I wait upon You. Renew my strength. Amen.' },
{ title: 'Tempted like as we are', ref: 'Hebrews 4:15', text: 'For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin.',
  speaker: 'The writer of Hebrews — on Jesus as our High Priest', plain: 'Jesus was tempted in the wilderness. He gets it. He\'s touched with your infirmities.', today: 'What temptation are you facing? He was tempted like you.', action: 'Bring your temptation to Him. He knows. He\'s been there.', prayer: 'Lord, You were tempted like me. Touch my infirmity. Amen.' },
{ title: 'God will provide', ref: 'Genesis 22:14', text: 'And Abraham called the name of that place Jehovah-jireh: as it is said to this day, In the mount of the LORD it shall be seen.',
  speaker: 'Moses recording Abraham\'s wilderness moment', plain: 'Jehovah-jireh. The LORD will provide. Abraham learned it on the mount.', today: 'What do you need provision for? Name it. He will be seen there.', action: 'Call your wilderness place Jehovah-jireh. "The LORD will provide."', prayer: 'Lord, in this mount, You shall be seen. Provide. Amen.' },
{ title: 'Strength of my heart', ref: 'Psalm 73:26', text: 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.',
  speaker: 'Asaph — after envy nearly broke him, before he saw God\'s end', plain: 'When body and heart fail, God remains the strength of your heart—and your portion.', today: 'You do not have to pretend you feel strong. He is the strength when you do not.', action: 'Say aloud: "My portion is God"—even if your flesh feels like it is failing.', prayer: 'Lord, my flesh and heart fail; be the strength of my heart forever. Amen.' },
{ title: 'Grace sufficient', ref: '2 Corinthians 12:9', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.',
  speaker: 'Paul — the Lord\'s answer to his thorn', plain: 'Weakness is not where grace ends. It is where Christ\'s power rests.', today: 'Where you feel weakest, ask for His strength—not to remove the thorn first.', action: 'Write one "infirmity" you will hand to Him today without fixing it yourself.', prayer: 'Lord, Your grace is sufficient; let Your power rest on my weakness. Amen.' }
  ];
  var cap40final = { title: '40 days complete', ref: 'Deuteronomy 8:2', text: 'And thou shalt remember all the way which the LORD thy God led thee these forty years in the wilderness, to humble thee, and to prove thee, to know what was in thine heart, whether thou wouldest keep his commandments, or no.',
  speaker: 'Moses — to Israel before the promised land', plain: 'Forty days in the wilderness shows what\'s really in your heart. You made it.', today: 'The testing revealed where you\'re strong and where you still need Him more.', action: 'Take 5 quiet minutes. Remember the hardest day in this plan. See how God showed up. Then share one lesson from these 40 days with someone—or write it down if you\'re not ready.', prayer: 'Father, You led me through these forty days. Thank You for every provision, every test, every time You carried me when I couldn\'t walk. I\'m Yours. Amen.' };
  var wilderness11 = wilderness10.concat([cap40final]);
  // When Pain Won't Quit — 7-day plan (trench-honest copy; plans.html uses id painwontquit + key tdb-plan-painwontquit-day)
  var painWontQuit7 = [
{ title: 'This pain is real', ref: '2 Corinthians 12:9', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.',
  speaker: 'Paul — the Lord\'s answer to his thorn', plain: 'Some days the pain is so loud it drowns everything else out. You\'re not weak for feeling it. God doesn\'t always take the pain away, but He promises His grace will be enough right in the middle of it.', today: 'Right now, say out loud: "Lord, this hurts. I need Your grace today."', action: 'Write down the number 1–10 for how bad the pain is right now. Be honest.', prayer: 'Jesus, the pain is loud today. Your grace is supposed to be enough. Help me believe it. Amen.' },
{ title: 'I\'m still here', ref: 'Lamentations 3:22-23', text: 'It is of the LORD\'s mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.',
  speaker: 'Jeremiah — after honest grief, remembering who God is', plain: 'You woke up again even when you didn\'t want to. That counts. Every new morning is proof God hasn\'t given up on you yet.', today: 'Thank Him for one small thing that still works today (even if it\'s just that you can breathe).', action: 'Take 3 slow breaths and say "New mercies" on each exhale.', prayer: 'Lord, thank You I\'m still here. Your mercies are new this morning. Help me use them. Amen.' },
{ title: 'One verse, one breath', ref: 'Isaiah 41:10', text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.',
  speaker: 'God through Isaiah — to a weary people', plain: 'You don\'t have to conquer the whole day. Just this next breath. God is holding you up when your legs won\'t.', today: 'When the pain spikes, stop and whisper this verse — even if it\'s through gritted teeth.', action: 'Set a quiet reminder on your phone: "One verse, one breath."', prayer: 'Father, I\'m scared and hurting. Hold me up today. I\'m leaning on Your right hand. Amen.' },
{ title: 'I\'m allowed to rest', ref: 'Matthew 11:28', text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
  speaker: 'Jesus — inviting the worn-out', plain: 'Rest isn\'t quitting. Jesus invites tired, hurting people to come to Him. You\'re carrying a heavy load in your body. He sees it.', today: 'Lie down or elevate your legs for 10 minutes and just tell Him how tired you are.', action: 'Do one thing today that eases the load even a little (ice, heat, stretch, whatever helps).', prayer: 'Jesus, I\'m heavy laden today. I\'m coming to You for rest. Give me some. Amen.' },
{ title: 'Others are hurting too', ref: 'Galatians 6:2', text: 'Bear ye one another\'s burdens, and so fulfil the law of Christ.',
  speaker: 'Paul — to churches learning to carry weight together', plain: 'Your pain is loud, but you\'re not the only one fighting today. Sometimes praying for someone else gives you a moment of relief.', today: 'Pray for one other person who\'s hurting right now (even if you don\'t know their name).', action: 'Leave one short anonymous line on the prayer wall (home or message board) for someone else.', prayer: 'Lord, someone else is in pain today too. Ease their burden and mine. Amen.' },
{ title: 'This won\'t last forever', ref: 'Revelation 21:4', text: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.',
  speaker: 'John — the vision of the new creation', plain: 'One day the pain ends. No more hell in your legs. No more tears. This world is broken, but it\'s not the end of the story.', today: 'Picture that day — no pain, no limping, just peace with Jesus.', action: 'Write down one thing you\'re looking forward to when the pain is gone.', prayer: 'Father, I\'m holding on for the day You wipe every tear and every pain away. Help me endure till then. Amen.' },
{ title: 'I\'m still fighting', ref: '2 Timothy 4:7', text: 'I have fought a good fight, I have finished my course, I have kept the faith:',
  speaker: 'Paul — at the end of his race', plain: 'You\'re still here — still showing up. That\'s fighting the good fight. God sees every small step you take through the hurt.', today: 'Look back at the last 7 days. See the small wins. Be proud of them.', action: 'Add this plan to your streak and tell someone (or just tell God) you finished it.', prayer: 'Lord, I\'m still in the trench. Thank You for every day I kept going. I want to finish well. Amen.' }
  ];
  // Cancer Comfort — 7-day plan (trench-honest; not medical advice; plans.html id cancercomfort; key tdb-plan-cancercomfort-day)
  // Psalms of Comfort — 7-day plan (same verse order as Bible Tool PSALMS_COMFORT_PLAN; plans.html id psalmscomfort; key tdb-plan-psalmscomfort-day)
  var psalmsComfort7 = [
{ title: 'The Lord is my shepherd', ref: 'Psalm 23:1', text: 'The LORD is my shepherd; I shall not want.',
  speaker: 'David — the shepherd-king, before the dark valley', plain: 'Comfort begins with belonging. You are not self-led in the noise—you have a Shepherd who does not lose sheep.', today: 'What are you trying to supply for yourself that He already names as His job?', action: 'Whisper the first line of this psalm once before you touch your phone today.', prayer: 'Lord, be my Shepherd. Teach my soul to stop grasping and start following. Amen.' },
{ title: 'Near the broken heart', ref: 'Psalm 34:18', text: 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.',
  speaker: 'David — after fear, after deliverance', plain: 'God does not wait for you to glue your heart back together. He draws near while it is still cracked.', today: 'Where does it feel like your spirit is crushed—and can you tell Him without fixing your tone first?', action: 'Write one honest sentence of grief or anxiety and end it with: "You are nigh."', prayer: 'Lord, my heart is broken. Draw near. Save me in the contrite place. Amen.' },
{ title: 'Refuge when trouble is loud', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — a song for shaky ground', plain: 'Trouble is not proof He left. He is not a distant refuge—He is present help while the ground still moves.', today: 'What trouble is trying to name itself as "God is gone"?', action: 'Name the trouble out loud, then say: "Very present help." Pause five seconds.', prayer: 'God, be my refuge and strength today—not someday. Right now. Amen.' },
{ title: 'Light when fear names the room', ref: 'Psalm 27:1', text: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?',
  speaker: 'David — when enemies were real, not imagined', plain: 'Fear shrinks when you remember who lights the path and who holds your life—not your nerves.', today: 'Which fear is loudest—and what truth from this verse answers it without shouting?', action: 'Replace one "what if" today with: "The Lord is my light and my salvation."', prayer: 'Lord, be my light. Let fear step back when You step in. Amen.' },
{ title: 'Rest under His shadow', ref: 'Psalm 91:1', text: 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.',
  speaker: 'A song of shelter — for the one who stays close', plain: 'Comfort is not always a feeling. Sometimes it is shadow—cover you did not earn, shade because you stayed near.', today: 'Where are you living exposed—trying to be your own cover?', action: 'Sit for two minutes without solving anything. Abide: stay in one place with Him.', prayer: 'Most High, let me dwell in Your secret place. I want Your shadow, not my strain. Amen.' },
{ title: 'Where help comes from', ref: 'Psalm 121:1', text: 'I will lift up mine eyes unto the hills, from whence cometh my help.',
  speaker: 'A pilgrim song — for the journey you did not choose', plain: 'Help is not invented inside your chest. It comes from the Lord who keeps your going out and your coming in.', today: 'What hill are you staring at—diagnosis, silence, money, pain—and can you lift your eyes past it to Him?', action: 'Look out a window or at the sky once and pray one sentence: "My help comes from You."', prayer: 'Lord, I lift my eyes. My help comes from You—not from the size of the hill. Amen.' },
{ title: 'Known all the way through', ref: 'Psalm 139:1', text: 'O LORD, thou hast searched me, and known me.',
  speaker: 'David — before the wonder of being formed and seen', plain: 'You are not a problem to figure out alone. The God who searches you is not gathering evidence against you—He already knows, and He stays.', today: 'What part of you feels hidden, ashamed, or too much—and what changes if He knows it and still draws near?', action: 'Finish this line on paper: "Because You know me, I can tell You __________."', prayer: 'Lord, You have searched me and known me. Thank You for love that knows all of me. Amen.' }
  ];
  // Proverbs Wisdom Sampler — same seven refs as Bible Tool PROVERBS_WISDOM_PLAN (plans.html id proverbswisdom)
  var proverbsWisdom7 = [
{ title: 'Where wisdom starts', ref: 'Proverbs 1:7', text: 'The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction.',
  speaker: 'Solomon — father to son — first lesson', plain: 'Wisdom does not begin with self-confidence. It begins with awe that fits God—not fear that runs from Him.', today: 'Where are you still trying to be your own smartest voice?', action: 'Before one decision today, pause and say: "What if fearing the Lord mattered more than looking smart?"', prayer: 'Lord, be the beginning of my knowledge. Teach me not to despise instruction. Amen.' },
{ title: 'Lean off your own map', ref: 'Proverbs 3:5', text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.',
  speaker: 'Solomon — same father, same steady hand', plain: 'Your understanding can be sincere and still wrong. Trust is whole-heart weight—not half on God, half on your read of the room.', today: 'What are you leaning on—schedule, anger, control—that is really "thine own understanding"?', action: 'Write one situation where you will trust first, plan second.', prayer: 'Lord, I trust You with all my heart. I lean off my own understanding. Amen.' },
{ title: 'Knowledge of the holy', ref: 'Proverbs 9:10', text: 'The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding.',
  speaker: 'Solomon — wisdom personified calls', plain: 'Wisdom is not a vibe. It starts with knowing who God is—holy—and letting that reorder you.', today: 'Where do you need "understanding" that lines up with God\'s character, not just what feels workable?', action: 'Read this verse twice slowly. Underline one word in your mind to carry today.', prayer: 'Holy God, be the beginning of my wisdom. Give me understanding that honors You. Amen.' },
{ title: 'Soft answer', ref: 'Proverbs 15:1', text: 'A soft answer turneth away wrath: but grievous words stir up anger.',
  speaker: 'Solomon — watching words land', plain: 'You cannot control someone else\'s heat. You can choose a soft answer so wrath does not get more fuel.', today: 'Where is a hard word waiting on your tongue?', action: 'Send or speak one sentence that is softer than your first draft—without being fake.', prayer: 'Lord, let my answer be soft enough to turn wrath away. Amen.' },
{ title: 'Commit the works', ref: 'Proverbs 16:3', text: 'Commit thy works unto the LORD, and thy thoughts shall be established.',
  speaker: 'Solomon — on work and clarity', plain: 'Clarity often follows surrender. Commit the works—not just the worry about them.', today: 'What project, conversation, or burden have you not actually handed to Him?', action: 'Name one "work" out loud: "I commit this to You." Then do the next small faithful step.', prayer: 'Lord, I commit my works to You. Establish my thoughts. Amen.' },
{ title: 'Train and tend', ref: 'Proverbs 22:6', text: 'Train up a child in the way he should go: and when he is old, he will not depart from it.',
  speaker: 'Solomon — long view on formation', plain: 'Training is direction over drama. It is faithful repetition—not perfect performance.', today: 'Who are you shaping—a child, a student, your own habits—and what "way" are you actually showing?', action: 'One concrete act of patience or instruction today that matches the way you say you want to go.', prayer: 'Lord, help me train faithfully. Give me patience for the long arc. Amen.' },
{ title: 'Praise that lasts', ref: 'Proverbs 31:30', text: 'Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised.',
  speaker: 'Solomon — closing a poem of strength', plain: 'What flatters fades. What fears the Lord and walks in truth lasts—and gets named with honor.', today: 'Where are you chasing favor or image instead of fearing the Lord?', action: 'Thank God for one person whose faithfulness is deeper than appearance.', prayer: 'Lord, let fearing You be what I want praised in me. Amen.' }
  ];
  // Hope in Uncertainty — hope-focused (distinct from the trust plan path); plans.html id hopeuncertain
  var hopeUncertainty7 = [
{ title: 'The God of hope', ref: 'Romans 15:13', text: 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.',
  speaker: 'Paul — blessing believers with hope that overflows', plain: 'Hope here is not a mood. It is supplied—filled—by the God who is hope Himself.', today: 'Where does your hope feel thin—and can you ask to abound, not just survive?', action: 'Pray one sentence: "Fill me with joy and peace in believing." Mean it slowly.', prayer: 'God of hope, fill me. Let me abound in hope by Your Spirit. Amen.' },
{ title: 'Anchor inside the veil', ref: 'Hebrews 6:19', text: 'Which hope we have as an anchor of the soul, both sure and stedfast, and which entereth into that within the veil;',
  speaker: 'The writer of Hebrews — hope that holds in storms', plain: 'When the future is fog, hope is not a guess. It is anchored—sure—inside the veil where Christ has gone before you.', today: 'What anxiety feels like drifting—and what would it change to picture an anchor set?', action: 'Draw a small anchor on paper or in notes; write one word beside it: "stedfast."', prayer: 'Lord, my soul needs an anchor. Hold me sure inside the veil. Amen.' },
{ title: 'Wait in His word', ref: 'Psalm 130:5', text: 'I wait for the LORD, my soul doth wait, and in his word do I hope.',
  speaker: 'The psalmist — out of the depths, still waiting', plain: 'Waiting is not doing nothing. It is aiming your hope at His word—not at the news feed.', today: 'What are you waiting for—and have you brought that wait to Scripture?', action: 'Read Psalm 130:5 five times. Let your soul wait one minute in silence.', prayer: 'Lord, I wait for You. In Your word I hope. Amen.' },
{ title: 'Rejoice, endure, pray', ref: 'Romans 12:12', text: 'Rejoicing in hope; patient in tribulation; continuing instant in prayer;',
  speaker: 'Paul — practical theology for hard weeks', plain: 'Hope does not cancel tribulation. It gives you patience inside it—and prayer keeps the line open.', today: 'Which of the three—rejoicing, patience, prayer—needs your attention most today?', action: 'Do a sixty-second prayer walk: one thank-you, one honest tribulation line, one request.', prayer: 'Lord, I rejoice in hope. Make me patient. Keep me instant in prayer. Amen.' },
{ title: 'Strength for the wait', ref: 'Isaiah 40:31', text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
  speaker: 'Isaiah — to exiles who felt finished', plain: 'Waiting on the Lord is not stalled living. It is how strength gets renewed when you have none left.', today: 'Are you trying to sprint answers—or wait long enough for strength to return?', action: 'Sit still three minutes. No phone. Whisper: "I wait upon the LORD."', prayer: 'Lord, renew my strength. I wait on You. Amen.' },
{ title: 'Expectation from Him', ref: 'Psalm 62:5', text: 'My soul, wait thou only upon God; for my expectation is from him.',
  speaker: 'David — when power and betrayal pressed in', plain: 'Expectation is pointed somewhere. Aim it at Him only—so disappointment does not own your week.', today: 'What expectation have you pinned on a person or outcome that belongs first on God?', action: 'Rewrite one hope as a sentence starting with: "My expectation is from God for..."', prayer: 'Lord, my soul waits only on You. My expectation is from You. Amen.' },
{ title: 'Hope and quiet waiting', ref: 'Lamentations 3:24-26', text: 'The LORD is my portion, saith my soul; therefore will I hope in him. The LORD is good unto them that wait for him, to the soul that seeketh him. It is good that a man should both hope and quietly wait for the salvation of the LORD.',
  speaker: 'Jeremiah — after honest grief, choosing hope', plain: 'Hope here is stubborn loyalty to God\'s goodness—not denial of pain. Quiet waiting is strength, not weakness.', today: 'What would "quiet waiting" look like in your loudest worry?', action: 'Finish seven days by writing: "Because of hope in Him, I will quietly wait for __________."', prayer: 'Lord, You are my portion. I hope in You. Teach me quiet waiting. Amen.' }
  ];
  // Gospel of John — seven-day sampler (John book intro + same arc as core "I am" passages); plans.html id gospeljohn
  var gospelJohn7 = [
{ title: 'In the beginning', ref: 'John 1:1', text: 'In the beginning was the Word, and the Word was with God, and the Word was God.',
  speaker: 'John — opening his Gospel', plain: 'Before your week started, the Word was. Your story does not begin with chaos—it begins with Christ.', today: 'What feels like "beginning" in your life right now—and who is really first?', action: 'Read John 1:1–5 in the chapter reader when you can. Let the first verse settle.', prayer: 'Lord, You are the Word. Be first in my mind today. Amen.' },
{ title: 'God so loved', ref: 'John 3:16', text: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.',
  speaker: 'Jesus — speaking to Nicodemus by night', plain: 'Love moved first. Believing is not earning—it is receiving what was already given.', today: 'Where do you feel "perishing" in worry or habit—and can you believe He gave His Son for that too?', action: 'Say John 3:16 out loud once. Let "whosoever" include you.', prayer: 'Father, thank You for giving Your Son. I believe; hold me in everlasting life. Amen.' },
{ title: 'Living water', ref: 'John 4:14', text: 'But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life.',
  speaker: 'Jesus — at the well with a woman who knew thirst', plain: 'Thirst returns when you drink from the wrong wells. He offers water that becomes a spring inside you.', today: 'What are you drinking from—approval, escape, control—that leaves you thirsty again?', action: 'Drink a glass of water slowly. Pray: "Lord, be my living water today."', prayer: 'Jesus, spring up in me. I want water that lasts. Amen.' },
{ title: 'Bread of life', ref: 'John 6:35', text: 'And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.',
  speaker: 'Jesus — after the feeding of the five thousand', plain: 'Hungry souls need more than distraction. Coming to Him is how hunger and thirst get answered.', today: 'What are you "feeding" on that is not bread?', action: 'Come to Him in one honest sentence before your next meal.', prayer: 'Lord, I come. Be my bread of life. Amen.' },
{ title: 'The good shepherd', ref: 'John 10:11', text: 'I am the good shepherd: the good shepherd giveth his life for the sheep.',
  speaker: 'Jesus — naming His care and His cost', plain: 'A good shepherd does not abandon sheep when wolves come. He gives His life—so you are not left alone.', today: 'Where do you feel like scattered sheep—and can you listen for His voice?', action: 'Name one way you will follow one small step of obedience today.', prayer: 'Good Shepherd, I hear You. Lead me. Thank You for laying down Your life. Amen.' },
{ title: 'The way, truth, life', ref: 'John 14:6', text: 'Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.',
  speaker: 'Jesus — comforting troubled disciples', plain: 'When the path is unclear, He does not only point a way—He is the way. Truth and life come with Him.', today: 'What feels blocked—and can you bring it to the Way, not just to worry?', action: 'Write "way, truth, life" on a card. Glance at it when anxiety narrows your view.', prayer: 'Lord, You are my way, truth, and life. Bring me to the Father. Amen.' },
{ title: 'Written that ye might believe', ref: 'John 20:31', text: 'But these are written, that ye might believe that Jesus is the Christ, the Son of God; and that believing ye might have life through his name.',
  speaker: 'John — stating why he wrote', plain: 'This Gospel is for faith that turns into life—not information that stays on the page.', today: 'After seven days in John, what do you believe more clearly about Jesus—and what life does that ask of you?', action: 'Tell God one sentence of thanks for something you saw in John this week.', prayer: 'Lord, I believe Jesus is the Christ, the Son of God. Give me life through His name. Amen.' }
  ];
  // Galatians: Freedom in Christ — 7-day plan (plans.html id galatiansfreedom; key tdb-plan-galatiansfreedom-day)
  var galatiansFreedom7 = [
{ title: 'Delivered for His will', ref: 'Galatians 1:4', text: 'Who gave himself for our sins, that he might deliver us from this present evil world, according to the will of God and our Father:',
  speaker: 'Paul — opening shot: grace before rules', plain: 'Christ gave Himself—first—to deliver you from a world system that trains you to perform. The will of God starts with rescue, not scorekeeping.', today: 'Where do you still feel measured instead of loved?', action: 'Say slowly: "He gave Himself for my sins—to deliver me." Let it land.', prayer: 'Lord, deliver me from performance religion. I receive Your will. Amen.' },
{ title: 'Crucified with Christ', ref: 'Galatians 2:20', text: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.',
  speaker: 'Paul — the center of Christian identity', plain: 'Your old self-justifying life ended at the cross. What lives now is Christ in you—by faith, not flexing.', today: 'Where are you still trying to be "I" instead of letting Christ live?', action: 'Write one sentence: "Not I—but Christ in me—in __________."', prayer: 'Jesus, I am crucified with You. Live in me where I keep grabbing the wheel. Amen.' },
{ title: 'Redeemed from the curse', ref: 'Galatians 3:13', text: 'Christ hath redeemed us from the curse of the law, being made a curse for us: for it is written, Cursed is every one that hangeth on a tree:',
  speaker: 'Paul — explaining the cross in plain terms', plain: 'The curse the law pronounces—Christ carried it. You are not buying your way back; you are redeemed.', today: 'What guilt still sounds like a curse—and needs the tree?', action: 'Read the verse once, then thank God for one specific mercy you could not earn.', prayer: 'Lord, You were made a curse for me. Thank You. Amen.' },
{ title: 'Abba, Father', ref: 'Galatians 4:6', text: 'And because ye are sons, God hath sent forth the Spirit of his Son into your hearts, crying, Abba, Father.',
  speaker: 'Paul — adoption, not orphan fear', plain: 'The Spirit does not coach you from the sidelines—He cries from inside you toward a Father who receives you.', today: 'When did you last pray "Abba" like a child—not like a defendant?', action: 'Pray one sentence starting with "Abba" about what you need today.', prayer: 'Abba, Father, I am Yours. Receive me again. Amen.' },
{ title: 'Stand fast in liberty', ref: 'Galatians 5:1', text: 'Stand fast therefore in the liberty wherewith Christ hath made us free, and be not entangled again with the yoke of bondage.',
  speaker: 'Paul — liberty as a posture, not chaos', plain: 'Freedom is not "do whatever." It is standing—unshaken—in what Christ won. Watch what tries to yoke you again.', today: 'What old yoke is knocking—approval, addiction to control, fear of man?', action: 'Name one yoke. Say: "I stand fast in liberty." Mean it once.', prayer: 'Lord, I stand fast in liberty. Do not let me go back to bondage. Amen.' },
{ title: 'Walk in the Spirit', ref: 'Galatians 5:25', text: 'If we live in the Spirit, let us also walk in the Spirit.',
  speaker: 'Paul — after the fruit of the Spirit', plain: 'Life in the Spirit is not a mood; it is a walk—daily, step by step—when feelings rise and fall.', today: 'Where does your walk look like the flesh winning today—and what would one Spirit step look like?', action: 'Before your next hard conversation, whisper: "Walk in the Spirit."', prayer: 'Spirit of God, I live in You—teach my feet to walk with You today. Amen.' },
{ title: 'Do not lose heart', ref: 'Galatians 6:9', text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.',
  speaker: 'Paul — closing a letter about freedom and love', plain: 'Freedom produces fruit that takes time. Weariness is not failure—fainting is quitting what love started.', today: 'What "well doing" feels unrewarded—and needs patience, not proof?', action: 'Finish seven days by writing one line of encouragement to yourself from this letter.', prayer: 'Lord, I am weary but I faint not in You. In due season, let me reap. Amen.' }
  ];
  // Suffering & Endurance — 7-day plan (plans.html id sufferendure; key tdb-plan-sufferendure-day); not a Bible Tool checklist
  var sufferingEndure7 = [
{ title: 'Glory in tribulation', ref: 'Romans 5:3-4', text: 'And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; And patience, experience; and experience, hope:',
  speaker: 'Paul — chains clanking, hope still standing', plain: 'Paul is not pretending pain is fun. He names a chain: pressure shapes patience, patience proves real, and proof deepens hope. None of that erases the tribulation—it gives it somewhere to go.', today: 'Where is tribulation pressing you—and can you tell God the truth about it without faking cheer?', action: 'Write one hard thing, then write one word after it: patience, experience, or hope—whichever fits today.', prayer: 'Lord, I do not pretend this is easy. Work patience in me. Let hope grow. Amen.' },
{ title: 'Let patience finish', ref: 'James 1:2-4', text: 'My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.',
  speaker: 'James — to people who knew pressure', plain: 'Joy here is not a fake smile. It is knowing trials are not wasted—faith is being exercised. Let patience finish; God is not in a hurry to leave you half-formed.', today: 'What temptation or trial is testing you—and what would "patience having her perfect work" look like today?', action: 'When stress spikes once today, pause ten seconds before you speak. Let patience get one word in first.', prayer: 'Lord, let patience have her perfect work. Make me entire, not just reactive. Amen.' },
{ title: 'Weak, then strong', ref: '2 Corinthians 12:9-10', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me. Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ\'s sake: for when I am weak, then am I strong.',
  speaker: 'Paul — the thorn still present, grace louder', plain: 'Christ\'s power rests where you cannot muscle through. Weakness is not failure—it is room for Him.', today: 'Where do you feel weakest—and can you stop apologizing to God for needing grace there?', action: 'Say aloud: "Your strength is made perfect in weakness." Mean it once.', prayer: 'Lord, Your grace is sufficient. Let Your power rest on my weakness. Amen.' },
{ title: 'After ye have suffered a while', ref: '1 Peter 5:10', text: 'But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.',
  speaker: 'Peter — to exiles who knew ache', plain: '"A while" can feel endless. God does not mock that. He promises to use suffering as a passage—not the final word—and to set you firm on the other side.', today: 'What part of your life still feels unsettled—and can you trust the God of all grace with the timeline?', action: 'Circle one area where you need to be "stablished." Pray that word once, slowly.', prayer: 'God of all grace, after suffering, establish and strengthen me. Settle me in You. Amen.' },
{ title: 'Looking unto Jesus', ref: 'Hebrews 12:1-2', text: 'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.',
  speaker: 'The writer of Hebrews — to runners getting tired', plain: 'You are not sprinting for applause. You run with patience because Jesus already ran through shame and finished. Eyes on Him—not on the hecklers.', today: 'What weight or besetting sin is slowing your run—and what would laying it aside look like today?', action: 'Read verse 2 once more. Whisper "Looking unto Jesus" before your next hard task.', prayer: 'Lord, I lay aside what I can. I look to Jesus, author and finisher. Amen.' },
{ title: 'Patience with joyfulness', ref: 'Colossians 1:11', text: 'Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness;',
  speaker: 'Paul — praying for a church under pressure', plain: 'Patience does not have to be grim. His might can hold you in longsuffering and still leave room for joy—not denial, but deep breath.', today: 'Where is longsuffering draining you—and could you ask for one small joy today that does not insult your pain?', action: 'Thank God for one small mercy out loud—food, breath, a friend, sleep.', prayer: 'Strengthen me with all might, Lord—unto patience and longsuffering with joyfulness. Amen.' },
{ title: 'The glory ahead', ref: 'Romans 8:18', text: 'For I reckon that the sufferings of this present time are not worthy to be compared with the glory which shall be revealed in us.',
  speaker: 'Paul — who knew suffering by experience', plain: 'This does not erase today. It measures it against a weight of glory you have not seen yet. Christ in you is the first taste; the full reveal is coming.', today: 'After seven days, what suffering feels heaviest—and can you hand it to the God who calls glory "not worthy to be compared"?', action: 'Write one line of hope that is honest—not hype—for the week ahead.', prayer: 'Lord, the sufferings are real. So is the glory. Hold me till it is revealed. Amen.' }
  ];
  // Psalms of Praise — 7-day plan (plans.html id psalmspraise; key tdb-plan-psalmspraise-day)
  var psalmsPraise7 = [
{ title: 'Enter with thanksgiving', ref: 'Psalm 100:1-5', text: 'Make a joyful noise unto the LORD, all ye lands. Serve the LORD with gladness: come before his presence with singing. Know ye that the LORD he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture. Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name. For the LORD is good; his mercy is everlasting; and his truth endureth to all generations.',
  speaker: 'The psalmist — a door flung open', plain: 'Praise is not performance. It is coming in noisy or quiet, knowing you belong—sheep with a good Shepherd, not orphans faking strength.', today: 'What would "serve the LORD with gladness" look like in your actual Tuesday?', action: 'Sing or hum one line of this psalm in the car, shower, or kitchen.', prayer: 'Lord, I enter with thanksgiving. You are good; Your mercy outlasts my mood. Amen.' },
{ title: 'Forget not His benefits', ref: 'Psalm 103:1-5', text: 'Bless the LORD, O my soul: and all that is within me, bless his holy name. Bless the LORD, O my soul, and forget not all his benefits: Who forgiveth all thine iniquities; who healeth all thy diseases; Who redeemeth thy life from destruction; who crowneth thee with lovingkindness and tender mercies; Who satisfieth thy mouth with good things; so that thy youth is renewed like the eagle\'s.',
  speaker: 'David — talking to his own soul', plain: 'Your soul needs directing, not just comfort. Blessing starts with remembering—forgiveness, healing, rescue—before you demand the next thing.', today: 'Which benefit do you forget first—forgiveness, healing, rescue—and can you name it back to God?', action: 'List three benefits on paper or in notes. Read them aloud.', prayer: 'Bless the LORD, O my soul—and all within me. I forget not Your benefits. Amen.' },
{ title: 'Sing to the Rock', ref: 'Psalm 95:1-7', text: 'O come, let us sing unto the LORD: let us make a joyful noise to the rock of our salvation. Let us come before his presence with thanksgiving, and make a joyful noise unto him with psalms. For the LORD is a great God, and a great King above all gods. In his hand are the deep places of the earth: the strength of the hills is his also. The sea is his, and he made it: and his hands formed the dry land. O come, let us worship and bow down: let us kneel before the LORD our maker. For he is our God; and we are the people of his pasture, and the sheep of his hand. To day if ye will hear his voice,',
  speaker: 'The psalmist — from song to kneeling', plain: 'Praise moves your body—voice, knees—because God is not a small thought. He holds depths and heights; you are sheep, not owners of the pasture.', today: 'Where has your heart been too proud to kneel—and can you kneel in spirit if not in body?', action: 'Stand or kneel for one minute. Offer one sentence of praise before you move on.', prayer: 'Rock of my salvation, I worship You—great King, my Maker. Amen.' },
{ title: 'Let everything praise', ref: 'Psalm 150:1-6', text: 'Praise ye the LORD. Praise God in his sanctuary: praise him in the firmament of his power. Praise him for his mighty acts: praise him according to his excellent greatness. Praise him with the sound of the trumpet: praise him with psaltery and harp. Praise him with timbrel and dance: praise him with stringed instruments and organs. Praise him upon the loud cymbals: praise him upon the high sounding cymbals. Let every thing that hath breath praise the LORD. Praise ye the LORD.',
  speaker: 'The psalms — ending the book with noise and breath', plain: 'Instruments and breath—God welcomes loud praise. If you have breath, you have a reason. Start there.', today: 'What "instrument" do you have today—voice, hands, work, care for kids—and can you aim it toward praise once?', action: 'Clap once, tap a rhythm, or speak "Praise ye the LORD" before bed.', prayer: 'Let my breath praise You, LORD. Praise ye the LORD. Amen.' },
{ title: 'Morning and night', ref: 'Psalm 92:1-4', text: 'It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High: To shew forth thy lovingkindness in the morning, and thy faithfulness every night, Upon an instrument of ten strings, and upon the psaltery; upon the harp with a solemn sound. For thou, LORD, hast made me glad through thy work: I will triumph in the works of thy hands.',
  speaker: 'The psalmist — a rhythm of thanks', plain: 'Morning and night bracket the day. Praise does not require a perfect day—only honest noticing of His lovingkindness and faithfulness.', today: 'What can you thank Him for this morning, and what from today will you thank Him for tonight?', action: 'Set two phone reminders: one word of thanks at each.', prayer: 'Most High, I show forth Your lovingkindness in the morning and Your faithfulness at night. Amen.' },
{ title: 'Great is the Lord', ref: 'Psalm 145:1-3', text: 'I will extol thee, my God, O king; and I will bless thy name for ever and ever. Every day will I bless thee; and I will praise thy name for ever and ever. Great is the LORD, and greatly to be praised; and his greatness is unsearchable.',
  speaker: 'David — extolling with no expiration date', plain: 'Praise is daily, not a spike. His greatness has no bottom—you will not run out of reasons.', today: 'What one attribute of God—kindness, strength, nearness—can you extol today without rushing?', action: 'Bless His name once an hour for three waking hours—one short sentence each time.', prayer: 'Great is the LORD. I bless Your name today—and the next day. Amen.' },
{ title: 'His wonderful works', ref: 'Psalm 107:1, 8', text: 'O give thanks unto the LORD, for he is good: for his mercy endureth for ever. Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men!',
  speaker: 'The psalmist — after stories of rescue, the same refrain', plain: 'Psalm 107 tells storm, prison, sickness, and trouble—then returns to this line after each story (verses 8, 15, 21, 31). Your life may repeat hard themes; His goodness and wonderful works are still the chorus.', today: 'Where have you seen rescue, even small—and can you join the refrain?', action: 'Text or tell one person one "wonderful work" you have seen God do.', prayer: 'O give thanks unto the LORD, for He is good. Let me praise You for Your goodness and wonderful works. Amen.' }
  ];
  // Family Worship in the Trenches — content array `familyWorshipTrenches7`. Plan engine id: familyworship;
  // progress localStorage key (do not rename): tdb-plan-familyworship-day.
  var familyWorshipTrenches7 = [
{ title: 'Gathered in His name', ref: 'Matthew 18:20', text: 'For where two or three are gathered together in my name, there am I in the midst of them.',
  speaker: 'Jesus — teaching about life together in His kingdom', plain: 'Family worship does not need a perfect house or a stage. Where two or three gather in His name, He draws near.', familySee: 'What stands out? Jesus promises His presence when His people gather—not when everything looks polished.', familyUnderstand: 'God is not distant while you clear the table or calm a toddler. He meets you in the middle of real rooms.', familyLive: 'Pick one meal or bedtime this week to read this verse aloud together and pause for ten seconds of quiet.', parentPrompt: 'Lead without performing: say one sentence about why you need Jesus in the room tonight.', kidQ: 'Where do you picture Jesus when we are all in the same room?', familyTogether: 'Pray one short sentence together: "Thank You for being with us."', prayer: 'Lord, be in the middle of our home—not as a show, but as truth. Thank You for meeting us when we gather in Your name. Amen.',
  drawPrompt: 'Draw your family together in one room (stick figures are enough). Add a small light or cross where Jesus is "in the midst."', talkTogether: 'When do we feel most "together" at home? When do we feel scattered?', oia58: 'What words does Jesus use? (two or three, gathered, name, midst.)', oia912: 'Why would Jesus care about two or three? What does "in my name" mean for our family?', oiaTeens: 'How is this different from "good vibes" or a family meeting? What changes if His presence is real?' },
{ title: 'Teach along the way', ref: 'Deuteronomy 6:7', text: 'And thou shalt teach them diligently unto thy children, and shalt talk of them when thou sittest in thine house, and when thou walkest by the way, and when thou liest down, and when thou risest up.',
  speaker: 'Moses — passing faith to the next generation', plain: 'Faith is meant to ride along with ordinary hours—not only on Sunday.', familySee: 'Notice when God says to talk: sitting, walking, lying down, rising—normal life.', familyUnderstand: 'God ties truth to daily rhythm. He wants His words in the traffic of your day.', familyLive: 'Choose one everyday moment this week (car line, dishes, bedtime) to say one true sentence about God.', parentPrompt: 'You will miss moments; grace exists. Name one natural slot this week where you can speak truth without a lecture.', kidQ: 'What is one place we go every week where we could talk about God for one minute?', familyTogether: 'Write three words on a sticky note for the fridge: "talk," "walk," "rest"—reminders from this verse.', prayer: 'Father, help our home sound like Your words—not nagging, not noise, but steady truth in ordinary hours. Amen.',
  drawPrompt: 'Draw four small pictures: at the table, on a walk, at bedtime, at breakfast—put a heart or Bible symbol in each.', talkTogether: 'What is one busy time when we could still say one thankful sentence to God?', oia58: 'List the times Moses names. Which one fits our week best?', oia912: 'What does "diligently" look like for a family—not perfect, but faithful?', oiaTeens: 'How does this verse challenge phone habits at the table or in the car?' },
{ title: 'Nurture, do not crush', ref: 'Ephesians 6:4', text: 'And, ye fathers, provoke not your children to wrath: but bring them up in the nurture and admonition of the Lord.',
  speaker: 'Paul — household instructions in Christ', plain: 'Correction can be loving—or it can train a child to flinch. God calls parents toward nurture.', familySee: 'Two commands: do not provoke; do bring up in the Lord\'s nurture and instruction.', familyUnderstand: 'God cares about the emotional climate of a home—not only outward behavior.', familyLive: 'This week, when correction comes, add one gentle sentence that names love before the rule.', parentPrompt: 'Ask yourself: "Am I provoking fear—or nurturing faith?" One honest answer is enough.', kidQ: 'What helps you feel safe when you mess up—yelling or calm words?', familyTogether: 'Agree on one family phrase for hard moments, such as: "We fix this together."', prayer: 'Lord, make our correction nurturing. Train our tone. Let love be louder than frustration. Amen.',
  drawPrompt: 'Draw a plant being watered (nurture) beside a small spark (provoking). Label them if you want.', talkTogether: 'What is one way we can say hard truth without making someone feel small?', oia58: 'What is the opposite of provoking, according to Paul?', oia912: 'What is the difference between anger that clears the air and anger that wounds?', oiaTeens: 'Where do you see "wrath" build up at home—and what would defuse it?' },
{ title: 'A heritage, not a hassle', ref: 'Psalm 127:3', text: 'Lo, children are an heritage of the LORD: and the fruit of the womb is his reward.',
  speaker: 'Solomon — a song of building and belonging', plain: 'On tired days children can feel like tasks. God names them as heritage—a gift with weight and wonder.', familySee: 'Heritage and reward—language of value, not burden.', familyUnderstand: 'God ties children to His generosity, not to our performance as parents.', familyLive: 'Name one child (or one younger friend) with a thankful sentence—out loud—this week.', parentPrompt: 'Guilt is loud in parenting. Let gratitude speak once today, even if the day was hard.', kidQ: 'What is something good God gave you that you did not earn?', familyTogether: 'Each person finishes: "Thank You for __________ in our family."', prayer: 'Thank You for the lives You placed in our home. Teach us to treat them as heritage, not hassle. Amen.',
  drawPrompt: 'Draw a gift tag that says "heritage" on something precious to your family.', talkTogether: 'What is one thing about our family that feels like a gift from God?', oia58: 'What two pictures does the psalm use for children?', oia912: 'How does calling children a "reward" change a stressful week?', oiaTeens: 'Where do you feel pressure to "perform" as a sibling or child—and how does grace answer that?' },
{ title: 'Direction over drama', ref: 'Proverbs 22:6', text: 'Train up a child in the way he should go: and when he is old, he will not depart from it.',
  speaker: 'Solomon — wisdom for the long road', plain: 'Training is not a single lecture. It is direction repeated with patience.', familySee: 'Train, way, old—this is a long picture, not a quick fix.', familyUnderstand: 'God honors faithful direction, even when the path wobbles.', familyLive: 'Pick one small habit to practice together for seven days (prayer, kindness, honesty). Keep it tiny.', parentPrompt: 'Where are you tempted to use volume instead of direction?', kidQ: 'What is one "way" our family is trying to walk—kindness, honesty, rest?', familyTogether: 'Circle one area to practice together this week; write it on the calendar.', prayer: 'Lord, train us in Your way. Give us patience for the long arc, not just the loud moment. Amen.',
  drawPrompt: 'Draw a path with two signposts: one says "train," one says "way."', talkTogether: 'What habit do we want to grow—not perfect, just truer?', oia58: 'What does "train up" suggest about repetition?', oia912: 'How is this verse misused—and how is it meant as mercy?', oiaTeens: 'What adult faith habit do you want to see modeled—honestly?' },
{ title: 'Do not discourage', ref: 'Colossians 3:21', text: 'Fathers, provoke not your children to anger, lest they be discouraged.',
  speaker: 'Paul — to a church learning new family rhythms', plain: 'Anger can be a habit in a home. God warns how it lands—in discouraged hearts.', familySee: 'The warning is emotional: anger leads to discouragement.', familyUnderstand: 'God cares about a child\'s inner courage, not only outward compliance.', familyLive: 'Before bed once this week, bless each child with one specific encouragement.', parentPrompt: 'Where does your tone land as discouragement—even when you are right?', kidQ: 'What words help you try again after a mistake?', familyTogether: 'Share one encouragement each—no backhanded compliments.', prayer: 'Jesus, guard our words. Let our home be a place where courage grows. Amen.',
  drawPrompt: 'Draw a shield labeled "courage" blocking arrows labeled "harsh words."', talkTogether: 'When have words made you want to give up—and when have they helped you try again?', oia58: 'What does Paul connect: anger and what outcome?', oia912: 'How can parents correct without discouraging?', oiaTeens: 'What would it look like to "rebuild" after a harsh moment at home?' },
{ title: 'Joy in truth', ref: '3 John 1:4', text: 'I have no greater joy than to hear that my children walk in truth.',
  speaker: 'John — an elder writing with fatherly warmth', plain: 'The Christian life ends in truth—not performance, not applause. Parents ache for children to walk in it.', familySee: 'Joy tied to hearing truth lived out.', familyUnderstand: 'God is pleased when children walk honestly with Christ—not when they merely look good.', familyLive: 'Finish the week with one honest family prayer: "Lord, help us walk in truth at home and away."', parentPrompt: 'Where do you need truth this week—confession, apology, courage?', kidQ: 'What is one true thing you want God to help you with?', familyTogether: 'Stand or hold hands. Thank God for one way you saw truth this week.', prayer: 'Lord, we want truth more than ease. Give us joy that matches walking with You. Amen.',
  drawPrompt: 'Draw footprints with the word "truth" on the path.', talkTogether: 'What does walking in truth look like in our house this week?', oia58: 'What kind of joy is John talking about?', oia912: 'Why is "walk" a good word for daily faith?', oiaTeens: 'Where is truth costly for you right now—and how can we support you?' }
  ];
  // Psalms of Comfort (Family Edition) — same seven KJV readings as Psalms of Comfort; family OIA + kid-ready prompts (plans.html id psalmscomfortfamily; key tdb-plan-psalmscomfortfamily-day)
  var psalmsComfortFamily7 = [
{ title: 'Shepherd care', ref: 'Psalm 23:1', text: 'The LORD is my shepherd; I shall not want.',
  speaker: 'David — before the valley', plain: 'Belonging comes first: you are not alone with your feelings—the Shepherd is with you.', familySee: 'What words describe God in this verse? (shepherd, want)', familyUnderstand: 'A shepherd leads and provides. God is not asking kids to be brave alone.', familyLive: 'At dinner, name one thing you are glad God takes care of for our family.', parentPrompt: 'Say one sentence: "We are not in charge of everything—and that is mercy."', kidQ: 'What does a shepherd do for sheep?', familyTogether: 'Whisper the first line of the psalm together once.', prayer: 'Lord, be our Shepherd. Teach us to trust Your care tonight. Amen.',
  drawPrompt: 'Draw a sheep and a shepherd staff—or a simple path with someone walking beside you.', talkTogether: 'What is something we worry about that we could hand to God?', oia58: 'Who is "my" shepherd—what does that word mean?', oia912: 'What might "I shall not want" mean when we still feel sad sometimes?', oiaTeens: 'Where do you try to be your own shepherd—and what would it look like to let God lead?' },
{ title: 'Near the sad heart', ref: 'Psalm 34:18', text: 'The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.',
  speaker: 'David — after fear, after deliverance', plain: 'God comes close when hearts feel cracked—not only when everyone is cheerful.', familySee: 'What two kinds of people does God draw near to?', familyUnderstand: 'God saves the humble, honest heart. He is not looking for a brave face.', familyLive: 'Each person shares one "small hard thing" from today—no fixing, just listening.', parentPrompt: 'Thank your kids for honest words, even if the tone was rough.', kidQ: 'When you cry, do you think God moves closer or farther?', familyTogether: 'Pray: "Thank You for being near when we are broken."', prayer: 'Lord, draw near to our broken places. Save us in the honest, quiet parts. Amen.',
  drawPrompt: 'Draw a heart with a crack and a gentle hand beside it (God\'s nearness).', talkTogether: 'What helps you feel heard at home—and what makes you hide feelings?', oia58: 'What does "nigh" mean in plain words?', oia912: 'Why might God care about a contrite spirit?', oiaTeens: 'Where do you fake "fine"—and what would safety look like if you did not have to?' },
{ title: 'Strong help in trouble', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — when the ground shakes', plain: 'Trouble is loud, but God is present—not far away.', familySee: 'Name three words that describe God here (refuge, strength, help).', familyUnderstand: 'He is especially near when life feels shaky.', familyLive: 'Do a "pause and breathe" together for 30 seconds—then say one true thing about God.', parentPrompt: 'Name the trouble without solving it in one sentence.', kidQ: 'What is a refuge—like a fort or a blanket fort?', familyTogether: 'Say together: "Very present help."', prayer: 'God, be our refuge and strength. Be very present in our trouble today. Amen.',
  drawPrompt: 'Draw a safe place (tent, house, or harbor) and label it "refuge."', talkTogether: 'What trouble feels loud right now—and what does God\'s nearness change?', oia58: 'What does "very present" mean?', oia912: 'How is God\'s help different from just "feeling better"?', oiaTeens: 'Where do you feel trouble trying to name itself as "God is gone"—and what is true instead?' },
{ title: 'Light and courage', ref: 'Psalm 27:1', text: 'The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?',
  speaker: 'David — when fear was real', plain: 'Fear names the room, but God names the light and the strength.', familySee: 'What questions does the psalm ask twice?', familyUnderstand: 'God is light and salvation—fear does not get the last word.', familyLive: 'Replace one worried "what if" tonight with: "The Lord is my light."', parentPrompt: 'Admit one fear in front of your kids, then point to God\'s care.', kidQ: 'What scares you at school or at night—and who helps you?', familyTogether: 'Whisper one fear, then read the first sentence of the verse slowly.', prayer: 'Lord, be our light and salvation. Turn down fear in our home. Amen.',
  drawPrompt: 'Draw a small candle or sun and write "light" near it.', talkTogether: 'What fear shrinks when we remember God is light?', oia58: 'What is God to David—light, salvation, strength?', oia912: 'Why ask "whom shall I fear" twice?', oiaTeens: 'Which fear feels biggest—and how does this verse answer without pretending life is easy?' },
{ title: 'Under His shadow', ref: 'Psalm 91:1', text: 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.',
  speaker: 'A song of shelter', plain: 'Staying close to God is like shade on a hot day—rest, not earning.', familySee: 'Where does the person dwell—and what do they get?', familyUnderstand: 'The Most High gives cover; we are invited to stay close.', familyLive: 'For two minutes, sit still together. No phones. Breathe. "Abide" means stay.', parentPrompt: 'Show kids what it looks like to rest in God—not rush.', kidQ: 'What is a shadow good for when the sun is hot?', familyTogether: 'Thank God for one way He has covered our family.', prayer: 'Most High, let us dwell in Your secret place. We want Your shadow, not our worry. Amen.',
  drawPrompt: 'Draw a big tree or umbrella labeled "shadow" and stick figures underneath.', talkTogether: 'Where do we feel exposed—and how can we "stay close" to God this week?', oia58: 'What is the secret place in simple words?', oia912: 'What does it mean to abide—not visit once?', oiaTeens: 'What competes with abiding—noise, schedule, shame?' },
{ title: 'Help for the journey', ref: 'Psalm 121:1', text: 'I will lift up mine eyes unto the hills, from whence cometh my help.',
  speaker: 'A pilgrim song', plain: 'Help does not start inside our chest. It comes from the Lord.', familySee: 'What does the psalmist do with his eyes?', familyUnderstand: 'God is the source of help for the whole trip—not only the easy miles.', familyLive: 'Look out a window or at the sky; pray one sentence: "My help comes from You."', parentPrompt: 'Name one "hill" (stress) and lift your eyes past it in prayer.', kidQ: 'Where do you look when you need help—phone, parent, God?', familyTogether: 'Finish: "My help comes from ________."', prayer: 'Lord, we lift our eyes. Our help comes from You—not from the size of the problem. Amen.',
  drawPrompt: 'Draw hills and a small figure looking up.', talkTogether: 'What hill is our family staring at—and how can we look to God first?', oia58: 'What action does the verse start with?', oia912: 'Why might a traveler need this song?', oiaTeens: 'What do you try to fix alone that belongs in prayer?' },
{ title: 'Known and loved', ref: 'Psalm 139:1', text: 'O LORD, thou hast searched me, and known me.',
  speaker: 'David — before the wonder of being seen', plain: 'Nothing in you scares God away. He already knows—and stays.', familySee: 'What two things does God do—search and know.', familyUnderstand: 'Being known is the start of comfort, not the end of hope.', familyLive: 'Each person finishes: "God knows me, and I can still talk to Him about __________."', parentPrompt: 'Tell your kids one way you are glad God knows you.', kidQ: 'Is it scary or good that God knows everything?', familyTogether: 'Thank God for loving what He knows.', prayer: 'Lord, You have searched us and known us. Thank You for love that stays. Amen.',
  drawPrompt: 'Draw a heart with the word "known" inside.', talkTogether: 'What part of life feels hidden—and how does God\'s knowing change that?', oia58: 'What does "searched" mean—like a caring parent checking in?', oia912: 'Why is "known" good news on a hard day?', oiaTeens: 'Where do you feel misunderstood—and how does God\'s knowing help?' }
  ];
  var cancerComfort7 = [
{ title: 'The word just hit', ref: 'Psalm 56:3', text: 'What time I am afraid, I will trust in thee.',
  speaker: 'David — afraid and still talking to God', plain: 'That moment the doctor said it\u2026 everything went quiet and loud at the same time. Your hands shook. Your mind started running every worst-case scenario. You don\'t have to pretend you\'re strong right now.', today: 'God doesn\'t shame you for being afraid. He asks you to bring the fear to Him\u2014even if it\'s ugly, even if it\'s screaming.', action: 'First: Right now, say out loud or whisper: \u201cLord, I\'m afraid.\u201d Don\'t dress it up. Just say it. Second: Write the word cancer on a piece of paper, then write But God\u2026 underneath. Leave it somewhere you\'ll see it today.', prayer: 'Jesus, the word cancer just wrecked me. I\'m scared. I don\'t know what to do with all this fear. I\'m trusting You with it anyway. Amen.' },
{ title: 'I\'m so tired already', ref: 'Matthew 11:28', text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
  speaker: 'Jesus — inviting the worn-out', plain: 'The appointments, the waiting, the scans, the needles\u2014it\'s only been a few days and you\'re already exhausted in your soul. You\'re allowed to be tired.', today: 'Jesus isn\'t asking you to be brave twenty-four seven. He\'s inviting the worn-out version of you to come rest on Him.', action: 'First: Find ten quiet minutes today. Sit or lie down and tell Him exactly how tired you are\u2014physically, emotionally, spiritually. Second: Cancel or shorten one non-essential thing today if you can. Give yourself permission to rest without guilt.', prayer: 'Lord, I\'m already so tired and this fight just started. Come close. Let me rest in You even when my body won\'t stop fighting. Amen.' },
{ title: 'Why me?', ref: 'Isaiah 55:8-9', text: 'For my thoughts are not your thoughts, neither are your ways my ways, saith the LORD. For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.',
  speaker: 'God through Isaiah — His ways are higher', plain: 'The anger and the why me hits hard. You see other people living normal lives while yours feels like it\'s falling apart. It\'s okay to feel that.', today: 'God doesn\'t always explain why, but He promises He\'s still good and He\'s still with you in the middle of the why.', action: 'First: Tell God the honest truth today\u2014even if it\'s \u201cI\'m mad at You.\u201d He can take it. Second: Write down three things you\'re angry about, then write I don\'t understand, but I\'m still Yours at the bottom.', prayer: 'Father, I don\'t understand why this is happening to me. Some days I\'m angry, some days I\'m numb. Hold me anyway. Amen.' },
{ title: 'My body feels like the enemy', ref: 'Psalm 139:14', text: 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.',
  speaker: 'The psalmist — before God who formed him', plain: 'Your own body turned on you. Scans, chemo, radiation\u2014it feels like betrayal from the inside. You look in the mirror and barely recognize yourself.', today: 'Even now, God still calls your body fearfully and wonderfully made. He sees the cancer and He sees you.', action: 'First: Put your hand on the part of your body that hurts most right now and say \u201cLord, this is Yours too.\u201d Second: Do one small gentle thing for your body today\u2014extra water, soft blanket, favorite pillow\u2014as kindness, not denial.', prayer: 'Jesus, my own body feels like it\'s fighting me. I feel betrayed. Remind me I\'m still Yours\u2014every sick cell, every weak part. Amen.' },
{ title: 'I feel so alone', ref: 'Deuteronomy 31:6', text: 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.',
  speaker: 'Moses — charging a frightened people', plain: 'Even when people are around, you can feel completely alone in this fight. The fear is yours. The pain is yours. The unknown is yours.', today: 'God doesn\'t just send help\u2014He comes with you. He\'s not watching from a distance.', action: 'First: Talk to Him like He\'s sitting right beside you in the chemo chair or in the waiting room. Second: Text or call one person today and say \u201cI\'m struggling today\u201d\u2014even if it\'s just one sentence.', prayer: 'Lord, I feel so alone in this. Everyone else gets to live normal days. Don\'t leave me. Walk with me through every appointment, every night I can\'t sleep. Amen.' },
{ title: 'What if I don\'t make it?', ref: '2 Corinthians 5:1', text: 'For we know that if our earthly house of this tabernacle were dissolved, we have a building of God, an house not made with hands, eternal in the heavens.',
  speaker: 'Paul — writing believers who knew suffering', plain: 'The fear of dying or leaving your family hits different at 3 a.m. You\'re not weak for thinking about it.', today: 'If the worst happens, it\'s not the end of your story\u2014just the end of this broken body.', action: 'First: Write a short note to the people you love most\u2014things you want them to know if you don\'t get to say them later. Second: Read Revelation 21:4 out loud and let yourself cry if you need to.', prayer: 'Father, I\'m scared I might not make it. If this is my road, hold my family. And hold me. I want to be with You without pain one day. Amen.' },
{ title: 'I\'m still here today', ref: 'Lamentations 3:22-23', text: 'It is of the LORD\'S mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.',
  speaker: 'Jeremiah — after honest grief, remembering mercy', plain: 'You made it through another week. Some days you wanted to quit. Some days you just wanted the pain to stop. But you\'re still here.', today: 'Every new morning is proof God\'s mercy is still chasing you\u2014even on the worst days of cancer.', action: 'First: Look back at the last seven days and name one small thing you\'re thankful for\u2014even if it\'s just I woke up today. Second: Share one honest sentence from this plan on the prayer wall or with someone who loves you.', prayer: 'Lord, thank You I\'m still here. Thank You for every hard breath, every tear, every moment You carried me when I couldn\'t stand. Your mercies really are new. Amen.' }
  ];
  var common20 = core9.concat(post4, mid7);
  global.TDB_PLANS_BATTLE_SHARED = {
    core9: core9,
    post4: post4,
    mid7: mid7,
    common20: common20,
    tail8: tail8,
    cap10: cap10,
    cap14: cap14,
    cap21: cap21,
    cap30deep: cap30deep,
    cap30final: cap30final,
    cap40final: cap40final,
    capWildernessBridge: capWildernessBridge,
    preCap30: preCap30,
    wilderness11: wilderness11,
    painWontQuit7: painWontQuit7,
    psalmsComfort7: psalmsComfort7,
    proverbsWisdom7: proverbsWisdom7,
    hopeUncertainty7: hopeUncertainty7,
    gospelJohn7: gospelJohn7,
    galatiansFreedom7: galatiansFreedom7,
    sufferingEndure7: sufferingEndure7,
    psalmsPraise7: psalmsPraise7,
    cancerComfort7: cancerComfort7,
    familyWorshipTrenches7: familyWorshipTrenches7,
    psalmsComfortFamily7: psalmsComfortFamily7
  };
})(typeof window !== 'undefined' ? window : globalThis);
