/**
 * Shared day rows for multi-length Battle plans (battle10/14/21/30/40).
 * Loaded by plans.html before the inline script. Single source — edit wording here.
 *
 * Authoring new plans: see docs/BATTLE-PLAN-AUTHORING.md (markdown draft template + wiring checklist).
 */
(function (global) {
  'use strict';
  var core9 = [
{ title: 'Name the noise', ref: 'Matthew 6:33', text: 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.',
  speaker: 'Jesus in the Sermon on the Mount', plain: 'Stop chasing the side things. Put God first and everything else lines up.', today: 'What are you scrolling toward instead of Him?', action: 'Set your phone face-down for 30 minutes and open the Word instead.', prayer: 'Lord, put You first today. Help me stop chasing what doesn\'t matter. Amen.' },
{ title: 'Guard the gate', ref: 'Philippians 4:8', text: 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, whatsoever things are of good report; if there be any virtue, and if there be any praise, think on these things.',
  speaker: 'Paul from prison — choosing his thoughts deliberately', plain: 'Your mind is a gate. You decide what gets in.', today: 'What content are you letting in that you wouldn\'t want God watching with you?', action: 'Unfollow or mute one account today that pulls you away from peace.', prayer: 'Father, guard my heart. Let me choose what gets in. Amen.' },
{ title: 'The enemy\'s tactic', ref: '1 Peter 5:8', text: 'Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour.',
  speaker: 'Peter to scattered believers under pressure', plain: 'Distraction isn\'t random. It\'s a strategy against you.', today: 'Where are you most distracted? That\'s likely where the attack is focused.', action: 'Name the distraction out loud. Then say: "I see you. I choose God."', prayer: 'God, I see the distraction. I choose You. Amen.' },
{ title: 'Renew the mind', ref: 'Romans 12:2', text: 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.',
  speaker: 'Paul calling believers to a different standard', plain: 'The world will shape you if you let it. Renewal is active, not passive.', today: 'What has the world\'s noise told you to believe this week?', action: 'Spend 5 minutes in Scripture before touching social media tomorrow morning.', prayer: 'Lord, renew my mind. Don\'t let the world shape me. Amen.' },
{ title: 'Stand firm', ref: 'Ephesians 6:13', text: 'Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all, to stand.',
  speaker: 'Paul — a prisoner writing about spiritual warfare', plain: 'You don\'t fight to win. You stand because God already won. Your job is to hold the ground.', today: 'What ground are you giving up through distraction?', action: 'Write down one boundary you will hold today. Keep it.', prayer: 'God, help me stand. I hold the ground You\'ve given. Amen.' },
{ title: 'Eyes on the prize', ref: 'Hebrews 12:1-2', text: 'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith.',
  speaker: 'The writer of Hebrews to a tired church', plain: 'Drop the weight. Stop looking sideways. Eyes on Jesus, keep running.', today: 'What weight — habit, app, person — slows your run?', action: 'Delete one app or break one habit that distracts you from the race.', prayer: 'Lord, eyes on Jesus. Drop the weight. Keep running. Amen.' },
{ title: 'The peace that guards', ref: 'Philippians 4:7', text: 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
  speaker: 'Paul — same letter, same prison, same peace', plain: 'God\'s peace doesn\'t make sense. It just shows up and stands guard anyway.', today: 'You\'ve battled distraction for 7 days. Where do you feel calmer?', action: 'Pray today: "Guard my heart and mind. Keep me focused on what matters." Then rest.', prayer: 'Father, guard my heart and mind. Keep me focused on what matters. Amen.' },
{ title: 'Keep thy heart', ref: 'Proverbs 4:23', text: 'Keep thy heart with all diligence; for out of it are the issues of life.',
  speaker: 'Solomon — father to son — on what matters most', plain: 'Everything flows from the heart. Guard it like your life depends on it. It does.', today: 'What is leaking out of your heart into your choices this week?', action: 'Pause before one decision today. Ask: "Is this from a guarded heart or a leaky one?"', prayer: 'Lord, keep my heart. Guard what flows out. Amen.' },
{ title: 'Cast down imaginations', ref: '2 Corinthians 10:5', text: 'Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ.',
  speaker: 'Paul — defending his ministry, teaching spiritual warfare', plain: 'Thoughts that oppose God don\'t get a free pass. Capture them. Bring them to Christ.', today: 'What thought has been running loose that needs to be brought captive?', action: 'Name one thought. Say: "I bring this to the obedience of Christ." Then release it.', prayer: 'Lord, I bring every thought captive to You. Amen.' },
  ];
  var post4 = [
{ title: 'Set affection above', ref: 'Colossians 3:2', text: 'Set your affection on things above, not on things on the earth.',
  speaker: 'Paul — redirecting the Colossians\' focus', plain: 'Affection follows where you set it. Choose above.', today: 'Where is your affection set — on things above or things on earth?', action: 'Before opening any app today, ask: "Is this above or below?" Choose one thing above.', prayer: 'Lord, set my affection on things above. Amen.' },
{ title: 'No man that warreth', ref: '2 Timothy 2:4', text: 'No man that warreth entangleth himself with the affairs of this life; that he may please him who hath chosen him to be a soldier.',
  speaker: 'Paul to Timothy — a young pastor in the fight', plain: 'Soldiers don\'t get tangled in civilian affairs. You\'re at war. Stay untangled.', today: 'What affair of this life has you entangled right now?', action: 'Name one entanglement. Pray: "I lay this down. I please You, not it."', prayer: 'Lord, I stay untangled. I please You. Amen.' },
{ title: 'One thing is needful', ref: 'Luke 10:41-42', text: 'And Jesus answered and said unto her, Martha, Martha, thou art careful and troubled about many things: But one thing is needful: and Mary hath chosen that good part, which shall not be taken away from her.',
  speaker: 'Jesus — at Martha\'s house — redirecting her focus', plain: 'Many things clamor. One thing is needful. Choose it.', today: 'What "many things" are you troubled about that aren\'t the one needful thing?', action: 'Sit with the Word for 10 minutes today. That\'s the good part. Choose it.', prayer: 'Lord, I choose the one needful thing. Amen.' },
{ title: 'Love not the world', ref: '1 John 2:15', text: 'Love not the world, neither the things that are in the world. If any man love the world, the love of the Father is not in him.',
  speaker: 'John — to believers who knew the cost of compromise', plain: 'You can\'t love the world and the Father. One will win.', today: 'What from the world are you still loving that competes with the Father?', action: 'Name it. Then say: "I choose the Father over this." Mean it.', prayer: 'Father, I choose You over the world. Amen.' },
  ];
  var mid7 = [
{ title: 'Be stedfast', ref: '1 Corinthians 15:58', text: 'Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.',
  speaker: 'Paul — after the resurrection chapter — calling for steadfastness', plain: 'Steadfast. Unmoveable. Your labour isn\'t in vain.', today: 'Where have you been moveable when you should have stood?', action: 'Pick one area. Be unmoveable there today.', prayer: 'Lord, I am steadfast. My labour is not in vain. Amen.' },
{ title: 'Walk circumspectly', ref: 'Ephesians 5:15-16', text: 'See then that ye walk circumspectly, not as fools, but as wise, Redeeming the time, because the days are evil.',
  speaker: 'Paul — on how to walk in a dark age', plain: 'Redeem the time. The days are evil. Walk like you know it.', today: 'How did you spend your time yesterday? Redeemed or wasted?', action: 'Redeem one hour today. Use it for something that matters.', prayer: 'Lord, I redeem the time. Walk circumspectly. Amen.' },
{ title: 'Unite my heart', ref: 'Psalm 86:11', text: 'Teach me thy way, O LORD; I will walk in thy truth: unite my heart to fear thy name.',
  speaker: 'David — in a psalm of dependence', plain: 'A divided heart scatters. Ask Him to unite it.', today: 'Is your heart united toward God or scattered toward a hundred things?', action: 'Pray this verse. Then notice one way your heart is divided. Bring it to Him.', prayer: 'Lord, unite my heart to fear Your name. Amen.' },
{ title: 'Watch and be sober', ref: '1 Thessalonians 5:6', text: 'Therefore let us not sleep, as do others; but let us watch and be sober.',
  speaker: 'Paul — to a church waiting for the Lord', plain: 'Don\'t sleepwalk through life. Watch. Be sober.', today: 'Where are you sleepwalking — numb to what matters?', action: 'Wake up in one area today. Pay attention. Be present.', prayer: 'Lord, I watch and am sober. I do not sleep. Amen.' },
{ title: 'Run not uncertainly', ref: '1 Corinthians 9:26', text: 'I therefore so run, not as uncertainly; so fight I, not as one that beateth the air.',
  speaker: 'Paul — on his own discipline as an athlete', plain: 'Run with purpose. Fight with aim. No beating the air.', today: 'Are you running uncertainly or with clear purpose?', action: 'Name the race you\'re in. Then run one step with intention today.', prayer: 'Lord, I run not uncertainly. I fight with aim. Amen.' },
{ title: 'Number our days', ref: 'Psalm 90:12', text: 'So teach us to number our days, that we may apply our hearts unto wisdom.',
  speaker: 'Moses — in a psalm about the brevity of life', plain: 'Numbered days make wise hearts. Don\'t waste them.', today: 'How many of your days have you applied to wisdom this month?', action: 'Count: how many days this week did you spend time in the Word? Add one.', prayer: 'Lord, teach me to number my days. Apply my heart to wisdom. Amen.' },
{ title: 'Abstain from lusts', ref: '1 Peter 2:11', text: 'Dearly beloved, I beseech you as strangers and pilgrims, abstain from fleshly lusts, which war against the soul.',
  speaker: 'Peter — to exiles who knew the cost of compromise', plain: 'Fleshly lusts war against the soul. Abstain. You\'re a pilgrim, not a settler.', today: 'What fleshly lust is warring against your soul right now?', action: 'Name it. Abstain from it for today. One day at a time.', prayer: 'Lord, I abstain. I am a pilgrim. Amen.' },
  ];
  var tail8 = [
{ title: 'Meditate day and night', ref: 'Joshua 1:8', text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.',
  speaker: 'God to Joshua — at the start of the promised land', plain: 'The Word in your mouth. Day and night. That\'s the rhythm.', today: 'How often is the Word in your mouth — or only in your feed?', action: 'Speak one verse out loud today. Let it depart from your mouth into the air.', prayer: 'Lord, the Word does not depart from my mouth. Amen.' },
{ title: 'Commit thy works', ref: 'Proverbs 16:3', text: 'Commit thy works unto the LORD, and thy thoughts shall be established.',
  speaker: 'Solomon — on the connection between commitment and clarity', plain: 'Commit your works. Then your thoughts get established. Order follows surrender.', today: 'What works have you not committed to Him?', action: 'Commit one thing to the Lord today — out loud. Then watch your thoughts.', prayer: 'Lord, I commit my works to You. Establish my thoughts. Amen.' },
{ title: 'Draw nigh to God', ref: 'James 4:8', text: 'Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and purify your hearts, ye double minded.',
  speaker: 'James — direct and practical', plain: 'Draw nigh. He draws nigh. It\'s a two-way move.', today: 'When did you last draw nigh — not out of duty, but desire?', action: 'Draw nigh today. One step. He meets you.', prayer: 'Lord, I draw nigh. Draw nigh to me. Amen.' },
{ title: 'Pure in heart', ref: 'Matthew 5:8', text: 'Blessed are the pure in heart: for they shall see God.',
  speaker: 'Jesus in the Beatitudes', plain: 'Purity of heart isn\'t perfection. It\'s single-mindedness. The pure see God.', today: 'Is your heart pure — single toward Him — or divided?', action: 'Ask Him to purify your heart in one area today. Receive it.', prayer: 'Lord, purify my heart. I want to see You. Amen.' },
{ title: 'Fear God', ref: 'Ecclesiastes 12:13', text: 'Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man.',
  speaker: 'The Preacher — after trying everything under the sun', plain: 'The whole duty. Fear God. Keep His commandments. Everything else is vanity.', today: 'Is fearing God the conclusion of your matter, or an afterthought?', action: 'Make fearing God the first thing today. Before the scroll. Before the task.', prayer: 'Lord, I fear You. I keep Your commandments. This is my duty. Amen.' },
{ title: 'Grace teaches', ref: 'Titus 2:11-12', text: 'For the grace of God that bringeth salvation hath appeared to all men, Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously, and godly, in this present world.',
  speaker: 'Paul to Titus — on what grace actually does', plain: 'Grace teaches. It doesn\'t excuse. It trains you to live soberly, righteously, godly.', today: 'Is grace teaching you — or are you using it as an excuse?', action: 'Let grace teach you one thing today. Deny one ungodly impulse.', prayer: 'Lord, Your grace teaches me. I live soberly, righteously, godly. Amen.' },
{ title: 'Iron sharpeneth iron', ref: 'Proverbs 27:17', text: 'Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.',
  speaker: 'Solomon — on the power of true friendship', plain: 'You need people who sharpen you. Not just affirm you. Sharpen.', today: 'Who sharpens you? Who do you sharpen?', action: 'Reach out to one person who sharpens you. Or become that for someone.', prayer: 'Lord, sharpen me through my friends. Let me sharpen others. Amen.' },
{ title: 'Already won', ref: '1 Corinthians 15:57', text: 'But thanks be to God, which giveth us the victory through our Lord Jesus Christ.',
  speaker: 'Paul after explaining the resurrection — the victory is the point', plain: 'You\'re not fighting for victory. You\'re fighting from it.', today: 'Start from victory, not toward it. The battle is already decided.', action: 'Face today\'s hardest thing from this place: "He already won this."', prayer: 'Thanks be to God. He already won. Amen.' },
  ];
  var cap10 = { title: '10 days in', ref: 'Psalm 119:105', text: 'Thy word is a lamp unto my feet, and a light unto my path.',
  speaker: 'The psalmist — after 176 verses on the Word', plain: 'You\'ve walked 10 days with the Word. It\'s lighting your path. Keep going.', today: 'Where has the Word lit your path this week?', action: 'Write down one way Scripture has guided you. Thank Him for it.', prayer: 'Lord, Your word is my lamp. Thank You for 10 days. Amen.' };
  var cap14 = { title: '14 days strong', ref: '1 Corinthians 15:58', text: 'Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord.',
  speaker: 'Paul — after the resurrection chapter — calling for steadfastness', plain: 'Two weeks in. Be steadfast. Unmoveable. Your labour isn\'t in vain.', today: 'You\'ve held the line for 14 days. What has shifted?', action: 'Write down one way you\'re more steadfast than when you started. Thank Him.', prayer: 'Lord, I am steadfast. My labour is not in vain. Thank You for 14 days. Amen.' };
  var cap21 = { title: '21 days — habit formed', ref: 'Joshua 1:8', text: 'This book of the law shall not depart out of thy mouth; but thou shalt meditate therein day and night, that thou mayest observe to do according to all that is written therein: for then thou shalt make thy way prosperous, and then thou shalt have good success.',
  speaker: 'God to Joshua — at the start of the promised land', plain: 'Three weeks in. The habit is forming. Don\'t let the Word depart from your mouth.', today: 'You\'ve built 21 days. How will you keep the Word in your mouth?', action: 'Commit to one way you\'ll continue — a time, a place, a rhythm. Write it down.', prayer: 'Lord, the Word does not depart from my mouth. Thank You for 21 days. Amen.' };
  var cap30deep = { title: '30 days deep', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'Not a distant help. A very present one. Right here. Right now.', today: 'You made it 30 days. Look at the ground you\'ve held. It\'s real.', action: 'Write down three ways you\'ve cut through distraction. Offer them back to Him.', prayer: 'Lord, You are my refuge and strength. Thank You for 30 days. Amen.' };
  var cap30final = { title: '30 days deep', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'A full month in the Word changes you. You\'ve built something real.', today: 'Even on the hardest days, you now reach for truth first instead of noise.', action: 'Look back at your first day. See how far He\'s carried you. Thank Him out loud. Then write one sentence: "Because of these 30 days, I now..."', prayer: 'Lord, thank You for every verse, every hard day, every small win. Keep building in me what You started. Amen.' };
  var capWildernessBridge = { title: '30 days — into the wilderness', ref: 'Psalm 46:1', text: 'God is our refuge and strength, a very present help in trouble.',
  speaker: 'The sons of Korah — after surviving what should have destroyed them', plain: 'Not a distant help. A very present one. Right here. Right now.', today: 'You made it 30 days. The next 10 are the wilderness stretch—trust, provision, temptation.', action: 'Write down one way God has been your refuge. Carry it into the next 10 days.',   prayer: 'Lord, You are my refuge and strength. I enter the wilderness with You. Amen.' };
  var preCap30 = { title: 'Do not weary', ref: 'Galatians 6:9', text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.',
  speaker: 'Paul — closing his letter to churches worn down by opposition', plain: 'Weariness is not failure. "Faint not" is permission to rest in Him—and keep sowing.', today: 'Day 29: you are not behind. In due season you will reap if you do not give up.', action: 'Name one small "well doing" you can keep today without performing for anyone.', prayer: 'Lord, I am weary but I faint not in You. Sustain me to day 30. Amen.' };
  var wilderness10 = [
{ title: 'Man shall not live by bread alone', ref: 'Matthew 4:4', text: 'But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.',
  speaker: 'Jesus — in the wilderness, tempted by the devil', plain: 'In the wilderness, provision isn\'t just food. It\'s every word from God.', today: 'What are you living by — bread alone, or His Word?', action: 'Let one verse from God\'s mouth feed you today. Sit with it.', prayer: 'Lord, I live by every word from Your mouth. Not bread alone. Amen.' },
{ title: 'He shall give his angels charge', ref: 'Psalm 91:11', text: 'For he shall give his angels charge over thee, to keep thee in all thy ways.',
  speaker: 'The psalmist — to one who dwells in the secret place', plain: 'In the wilderness, you\'re not alone. Angels have charge over you.', today: 'Where do you need to remember you\'re kept?', action: 'Name one "way" you\'re walking. Pray: "Keep me in this way."', prayer: 'Lord, Your angels have charge over me. I am kept. Amen.' },
{ title: 'Trust in the LORD', ref: 'Proverbs 3:5-6', text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
  speaker: 'Solomon — father to son — on the core of wisdom', plain: 'Wilderness seasons strip away your own understanding. Trust replaces it.', today: 'Where are you leaning on your own understanding instead of Him?', action: 'Acknowledge Him in one decision today. Let Him direct.', prayer: 'Lord, I trust You with all my heart. Direct my paths. Amen.' },
{ title: 'Bread from heaven', ref: 'Exodus 16:4', text: 'Then said the LORD unto Moses, Behold, I will rain bread from heaven upon you; and the people shall go out and gather a certain rate every day; that I may prove them, whether they will walk in my law, or no.',
  speaker: 'God to Moses — in the wilderness, before the manna', plain: 'God provided daily. Not a stockpile. Daily. That\'s the wilderness rhythm.', today: 'Are you gathering today\'s portion, or hoarding yesterday\'s?', action: 'Receive today\'s portion from God. Don\'t reach for tomorrow\'s yet.', prayer: 'Lord, rain bread from heaven. I gather today\'s rate. Amen.' },
{ title: 'The LORD is my shepherd', ref: 'Psalm 23:1', text: 'The LORD is my shepherd; I shall not want.',
  speaker: 'David — the shepherd-king — who knew wilderness and green pastures', plain: 'In the wilderness, the Shepherd leads. You shall not want.', today: 'What do you want that the Shepherd hasn\'t provided?', action: 'Say: "I shall not want." Mean it. Rest in it.', prayer: 'Lord, You are my Shepherd. I shall not want. Amen.' },
{ title: 'Wait on the LORD', ref: 'Isaiah 40:31', text: 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.',
  speaker: 'Isaiah — to exiles in their own wilderness', plain: 'Waiting isn\'t passive. It renews. Eagles, running, walking—all from waiting.', today: 'Where are you running ahead instead of waiting?', action: 'Wait on the Lord in one area today. Let Him renew your strength.', prayer: 'Lord, I wait upon You. Renew my strength. Amen.' },
{ title: 'Tempted like as we are', ref: 'Hebrews 4:15', text: 'For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin.',
  speaker: 'The writer of Hebrews — on Jesus as our High Priest', plain: 'Jesus was tempted in the wilderness. He gets it. He\'s touched with your infirmities.', today: 'What temptation are you facing? He was tempted like you.', action: 'Bring your temptation to Him. He knows. He\'s been there.', prayer: 'Lord, You were tempted like me. Touch my infirmity. Amen.' },
{ title: 'God will provide', ref: 'Genesis 22:14', text: 'And Abraham called the name of that place Jehovah-jireh: as it is said to this day, In the mount of the LORD it shall be seen.',
  speaker: 'Moses recording Abraham\'s wilderness moment', plain: 'Jehovah-jireh. The LORD will provide. Abraham learned it on the mount.', today: 'What do you need provision for? Name it. He will be seen there.', action: 'Call your wilderness place Jehovah-jireh. "The LORD will provide."', prayer: 'Lord, in this mount, You shall be seen. Provide. Amen.' },
{ title: 'Strength of my heart', ref: 'Psalm 73:26', text: 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.',
  speaker: 'Asaph — after envy nearly broke him, before he saw God\'s end', plain: 'When body and heart fail, God remains the strength of your heart—and your portion.', today: 'You do not have to pretend you feel strong. He is the strength when you do not.', action: 'Say aloud: "My portion is God"—even if your flesh feels like it is failing.', prayer: 'Lord, my flesh and heart fail; be the strength of my heart forever. Amen.' },
{ title: 'Grace sufficient', ref: '2 Corinthians 12:9', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.',
  speaker: 'Paul — the Lord\'s answer to his thorn', plain: 'Weakness is not where grace ends. It is where Christ\'s power rests.', today: 'Where you feel weakest, ask for His strength—not to remove the thorn first.', action: 'Write one "infirmity" you will hand to Him today without fixing it yourself.', prayer: 'Lord, Your grace is sufficient; let Your power rest on my weakness. Amen.' }
  ];
  var cap40final = { title: '40 days complete', ref: 'Deuteronomy 8:2', text: 'And thou shalt remember all the way which the LORD thy God led thee these forty years in the wilderness, to humble thee, and to prove thee, to know what was in thine heart, whether thou wouldest keep his commandments, or no.',
  speaker: 'Moses — to Israel before the promised land', plain: 'Forty days in the wilderness shows what\'s really in your heart. You made it.', today: 'The testing revealed where you\'re strong and where you still need Him more.', action: 'Take 5 quiet minutes. Remember the hardest day in this plan. See how God showed up. Then share one lesson from these 40 days with someone—or write it down if you\'re not ready.', prayer: 'Father, You led me through these forty days. Thank You for every provision, every test, every time You carried me when I couldn\'t walk. I\'m Yours. Amen.' };
  var wilderness11 = wilderness10.concat([cap40final]);
  // When Pain Won't Quit — 7-day plan (trench-honest copy; plans.html uses id painwontquit + key tdb-plan-painwontquit-day)
  var painWontQuit7 = [
{ title: 'This pain is real', ref: '2 Corinthians 12:9', text: 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.',
  speaker: 'Paul — the Lord\'s answer to his thorn', plain: 'Some days the pain is so loud it drowns everything else out. You\'re not weak for feeling it. God doesn\'t always take the pain away, but He promises His grace will be enough right in the middle of it.', today: 'Right now, say out loud: "Lord, this hurts. I need Your grace today."', action: 'Write down the number 1–10 for how bad the pain is right now. Be honest.', prayer: 'Jesus, the pain is loud today. Your grace is supposed to be enough. Help me believe it. Amen.' },
{ title: 'I\'m still here', ref: 'Lamentations 3:22-23', text: 'It is of the LORD\'s mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.',
  speaker: 'Jeremiah — after honest grief, remembering who God is', plain: 'You woke up again even when you didn\'t want to. That counts. Every new morning is proof God hasn\'t given up on you yet.', today: 'Thank Him for one small thing that still works today (even if it\'s just that you can breathe).', action: 'Take 3 slow breaths and say "New mercies" on each exhale.', prayer: 'Lord, thank You I\'m still here. Your mercies are new this morning. Help me use them. Amen.' },
{ title: 'One verse, one breath', ref: 'Isaiah 41:10', text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.',
  speaker: 'God through Isaiah — to a weary people', plain: 'You don\'t have to conquer the whole day. Just this next breath. God is holding you up when your legs won\'t.', today: 'When the pain spikes, stop and whisper this verse — even if it\'s through gritted teeth.', action: 'Set a quiet reminder on your phone: "One verse, one breath."', prayer: 'Father, I\'m scared and hurting. Hold me up today. I\'m leaning on Your right hand. Amen.' },
{ title: 'I\'m allowed to rest', ref: 'Matthew 11:28', text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
  speaker: 'Jesus — inviting the worn-out', plain: 'Rest isn\'t quitting. Jesus invites tired, hurting people to come to Him. You\'re carrying a heavy load in your body. He sees it.', today: 'Lie down or elevate your legs for 10 minutes and just tell Him how tired you are.', action: 'Do one thing today that eases the load even a little (ice, heat, stretch, whatever helps).', prayer: 'Jesus, I\'m heavy laden today. I\'m coming to You for rest. Give me some. Amen.' },
{ title: 'Others are hurting too', ref: 'Galatians 6:2', text: 'Bear ye one another\'s burdens, and so fulfil the law of Christ.',
  speaker: 'Paul — to churches learning to carry weight together', plain: 'Your pain is loud, but you\'re not the only one fighting today. Sometimes praying for someone else gives you a moment of relief.', today: 'Pray for one other person who\'s hurting right now (even if you don\'t know their name).', action: 'Leave one short anonymous line on the prayer wall (home or message board) for someone else.', prayer: 'Lord, someone else is in pain today too. Ease their burden and mine. Amen.' },
{ title: 'This won\'t last forever', ref: 'Revelation 21:4', text: 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.',
  speaker: 'John — the vision of the new creation', plain: 'One day the pain ends. No more hell in your legs. No more tears. This world is broken, but it\'s not the end of the story.', today: 'Picture that day — no pain, no limping, just peace with Jesus.', action: 'Write down one thing you\'re looking forward to when the pain is gone.', prayer: 'Father, I\'m holding on for the day You wipe every tear and every pain away. Help me endure till then. Amen.' },
{ title: 'I\'m still fighting', ref: '2 Timothy 4:7', text: 'I have fought a good fight, I have finished my course, I have kept the faith:',
  speaker: 'Paul — at the end of his race', plain: 'You\'re still here — still showing up. That\'s fighting the good fight. God sees every small step you take through the hurt.', today: 'Look back at the last 7 days. See the small wins. Be proud of them.', action: 'Add this plan to your streak and tell someone (or just tell God) you finished it.', prayer: 'Lord, I\'m still in the trench. Thank You for every day I kept going. I want to finish well. Amen.' }
  ];
  // Dealing with Cancer — 7-day plan (honest fear + Christ beside you; not medical advice; plans.html id cancercomfort)
  var cancerComfort7 = [
{ title: 'Afraid is allowed', ref: 'Psalm 56:3', text: 'What time I am afraid, I will trust in thee.',
  speaker: 'David — running from danger, still talking to God', plain: 'The word "cancer" can hit like a door slam. Fear does not disqualify you. David named fear and still chose trust in the same breath—not a neat fix, a direction.', today: 'You do not have to pretend you are fine. God already heard the news before you did.', action: 'Say out loud: "I am afraid—and I will trust You." If you can, tell one safe person how today actually feels.', prayer: 'Lord, I am afraid. I will trust You anyway. Stay with me in this. Amen.' },
{ title: 'When the body feels fragile', ref: 'Psalm 73:26', text: 'My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.',
  speaker: 'Asaph — after envy nearly broke him, before he saw God\'s end', plain: 'Treatment, fatigue, pain, waiting—they can make your body feel like the enemy. Scripture does not ask you to deny that. It says when flesh and heart fail, God remains the strength of your heart and your portion.', today: 'Weakness is not proof He left. It may be exactly where He meets you.', action: 'Place a hand on your chest. Whisper: "You are the strength of my heart." Rest one minute without fixing anything.', prayer: 'Father, my flesh and heart fail. Be the strength of my heart and my portion forever. Amen.' },
{ title: 'Heavy laden', ref: 'Matthew 11:28', text: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.',
  speaker: 'Jesus — inviting the worn-out', plain: 'Appointments, side effects, what-ifs, the way your mind runs at 3 a.m.—that is a heavy pack. Jesus does not say "toughen up." He says come, and He will give rest.', today: 'You are allowed to be tired in body and soul at the same time.', action: 'Write one line: what feels heaviest today. Fold the paper, hold it, and pray: "I hand this to You."', prayer: 'Jesus, I am heavy laden. I come to You for rest. Amen.' },
{ title: 'Carry the appointment to Him', ref: 'Philippians 4:6-7', text: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',
  speaker: 'Paul — writing from custody, still practicing peace', plain: 'Anxiety likes to sprint ahead of you. God invites you to bring the real requests—scans, results, side effects, the people you love—before Him with thanksgiving for who He is, not for pretending the danger is small.', today: 'Peace that passes understanding does not mean you understand everything. It means God guards your heart and mind while you wait.', action: 'Name one specific worry (aloud or on paper). End with: "I make this request known to You."', prayer: 'Lord, I am careful about much. I bring my requests to You. Let Your peace guard my heart and mind. Amen.' },
{ title: 'Hands that help', ref: 'Galatians 6:2', text: 'Bear ye one another\'s burdens, and so fulfil the law of Christ.',
  speaker: 'Paul — to churches learning to carry weight together', plain: 'You were not designed to haul this alone. Asking for a ride, a meal, someone to sit in the waiting room—that is not weakness. It is how the body of Christ obeys.', today: 'If pride or shame says "don\'t bother them," remember bearing burdens is part of their calling too.', action: 'Accept one small help this week—or ask for one. If no one is near, message one honest sentence to a trusted friend.', prayer: 'Lord, thank You for people who bear burdens. Help me receive help and give it. Amen.' },
{ title: 'Shadow valley', ref: 'Psalm 23:4', text: 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.',
  speaker: 'David — shepherd who knew dark valleys', plain: 'Some days feel like the valley of the shadow—not always because the end is near, but because illness casts a long shadow over ordinary life. The promise here is not the absence of shadows. It is presence: Thou art with me.', today: 'Evil and fear may knock. You do not walk the valley alone.', action: 'Read this verse slowly twice. On the second time, pause on "for thou art with me."', prayer: 'Good Shepherd, I walk through the valley. Be with me; comfort me with Your rod and staff. Amen.' },
{ title: 'Still held', ref: 'Romans 8:38-39', text: 'For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord.',
  speaker: 'Paul — after a chapter on suffering and hope', plain: 'Nothing on this list—not the diagnosis, not the treatment, not the worst night—can separate you from the love of God in Christ. That is not a slogan. It is Paul\'s settled verdict after counting every contender.', today: 'Seven days does not close the story. It opens a rhythm: truth on the days scans and side effects return.', action: 'Finish this sentence aloud: "Nothing can separate me from the love of God in Christ." Add one thing you are scared of—and say it again anyway.', prayer: 'Lord, I am persuaded on the days I feel it and on the days I don\'t. Hold me in Your love. Amen.' }
  ];
  var common20 = core9.concat(post4, mid7);
  global.TDB_PLANS_BATTLE_SHARED = {
    core9: core9,
    post4: post4,
    mid7: mid7,
    common20: common20,
    tail8: tail8,
    cap10: cap10,
    cap14: cap14,
    cap21: cap21,
    cap30deep: cap30deep,
    cap30final: cap30final,
    cap40final: cap40final,
    capWildernessBridge: capWildernessBridge,
    preCap30: preCap30,
    wilderness11: wilderness11,
    painWontQuit7: painWontQuit7,
    cancerComfort7: cancerComfort7
  };
})(typeof window !== 'undefined' ? window : globalThis);
