-- Seed a few daily battles (edit dates as needed)
insert into public.daily_battles (date, verse_ref, reflection, prayer)
values
  ('2026-02-05', 'Psalm 46:1', 'God is your refuge today. Breathe, pause, and let His strength steady you.', 'Lord, be my refuge and strength today. Amen.'),
  ('2026-02-06', 'Philippians 4:6-7', 'When anxiety rises, trade it for prayer and thanksgiving. Peace follows obedience.', 'Jesus, guard my heart and mind with Your peace. Amen.'),
  ('2026-02-07', 'Isaiah 41:10', 'Fear does not get the final word. God is with you and will uphold you.', 'Father, help me trust Your presence and strength. Amen.'),
  ('2026-02-08', 'Lamentations 3:22-23', 'Mercy is new today. Let yesterday’s weight fall off and receive fresh grace.', 'God, thank You for new mercies this morning. Amen.'),
  ('2026-02-09', 'Romans 8:28', 'God is working even the hard things for good. Stay faithful in the process.', 'Lord, help me trust Your purpose today. Amen.'),
  ('2026-02-10', 'Matthew 11:28', 'If you are weary, Jesus invites you to rest in Him today.', 'Jesus, give me Your rest and gentle strength. Amen.'),
  ('2026-02-11', 'Joshua 1:9', 'Courage grows when you remember God is with you in every step.', 'God, make me bold and steady today. Amen.'),
  ('2026-02-12', '1 Peter 5:7', 'You do not have to carry the burden alone. Hand it to God.', 'Father, I give You every worry today. Amen.'),
  ('2026-02-13', 'Psalm 34:18', 'God is near to the brokenhearted. You are not abandoned.', 'Lord, draw close and heal my heart. Amen.'),
  ('2026-02-14', '1 Corinthians 13:4-5', 'Love is patient and kind. Choose love in every conversation today.', 'Jesus, shape my heart to love like You. Amen.'),
  ('2026-02-15', 'Proverbs 3:5-6', 'Trust God with the path ahead and He will lead you clearly.', 'Lord, guide my steps today. Amen.'),
  ('2026-02-16', 'John 14:27', 'Peace is a gift from Jesus, not a reward for perfect circumstances.', 'Jesus, plant Your peace in me today. Amen.'),
  ('2026-02-17', 'Romans 12:12', 'Stay hopeful, patient, and faithful. God is working.', 'God, keep me steady in hope today. Amen.'),
  ('2026-02-18', 'Psalm 23:1', 'The Lord is your shepherd. You lack nothing you truly need.', 'Lord, shepherd my heart today. Amen.'),
  ('2026-02-19', '2 Timothy 1:7', 'God gives power, love, and a sound mind. Fear is not your portion.', 'Holy Spirit, fill me with Your strength today. Amen.'),
  ('2026-02-20', 'Hebrews 12:1', 'Lay down every weight and run with endurance today.', 'Jesus, help me run free and focused. Amen.'),
  ('2026-02-21', 'Psalm 91:1-2', 'You are safe under God’s shelter. Rest in His protection.', 'Lord, be my refuge today. Amen.'),
  ('2026-02-22', 'Micah 6:8', 'Choose justice, mercy, and humility in every step today.', 'God, shape my actions with Your heart. Amen.'),
  ('2026-02-23', 'James 1:5', 'Ask for wisdom and God will give it generously.', 'Father, give me wisdom today. Amen.'),
  ('2026-02-24', 'Galatians 6:9', 'Do not grow weary in doing good. A harvest is coming.', 'Lord, strengthen me to keep doing good. Amen.'),
  ('2026-02-25', 'Isaiah 43:2', 'God is with you through fire and flood. You will not be overwhelmed.', 'God, hold me steady through every trial. Amen.'),
  ('2026-02-26', 'Psalm 27:1', 'The Lord is your light and salvation. Fear loses its grip.', 'Jesus, be my light today. Amen.'),
  ('2026-02-27', 'Ephesians 6:10', 'Be strong in the Lord and His mighty power today.', 'Lord, clothe me with Your strength. Amen.'),
  ('2026-02-28', 'Matthew 6:33', 'Seek God first and He will provide what you need.', 'Father, keep my priorities right today. Amen.'),
  ('2026-03-01', 'Colossians 3:23', 'Work with all your heart as for the Lord.', 'Jesus, help me serve with joy today. Amen.'),
  ('2026-03-02', 'Psalm 119:105', 'God’s Word lights your path step by step.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-03-03', '1 John 1:9', 'Confession restores fellowship. God is faithful to forgive.', 'Lord, cleanse and renew me today. Amen.'),
  ('2026-03-04', 'Romans 15:13', 'God fills you with joy and peace as you trust Him.', 'God, fill me with joy and peace today. Amen.'),
  ('2026-03-05', 'Zephaniah 3:17', 'God is with you and rejoices over you with singing.', 'Father, remind me of Your love today. Amen.'),
  ('2026-03-06', 'John 15:5', 'Stay connected to Jesus to bear lasting fruit.', 'Jesus, keep me close to You today. Amen.'),
  ('2026-03-07', 'Hebrews 4:16', 'Approach God’s throne with confidence and find help.', 'Lord, I come to You for help today. Amen.'),
  ('2026-03-08', 'Psalm 37:5', 'Commit your way to the Lord and He will act.', 'God, I commit this day to You. Amen.'),
  ('2026-03-09', '1 Thessalonians 5:16-18', 'Rejoice, pray, and give thanks in all things.', 'Lord, help me practice joy and gratitude today. Amen.'),
  ('2026-03-10', '2 Corinthians 12:9', 'Gods grace is sufficient; His power is made perfect in weakness.', 'Jesus, show Your strength in my weakness today. Amen.'),
  ('2026-03-11', 'Psalm 121:1-2', 'Help comes from the Lord who made heaven and earth.', 'Lord, I lift my eyes to You today. Amen.'),
  ('2026-03-12', 'Matthew 5:16', 'Let your light shine so others see Gods goodness in you.', 'Jesus, make my life a light today. Amen.'),
  ('2026-03-13', 'Proverbs 16:3', 'Commit your plans to the Lord and He will establish them.', 'God, establish my steps today. Amen.'),
  ('2026-03-14', 'Psalm 62:1', 'Find quiet rest in God alone. He is your salvation.', 'Lord, quiet my soul in You today. Amen.'),
  ('2026-03-15', 'John 8:12', 'Jesus is the light of the world. Follow Him and do not walk in darkness.', 'Jesus, light my path today. Amen.'),
  ('2026-03-16', 'Isaiah 40:31', 'Wait on the Lord and your strength will be renewed.', 'Father, renew my strength today. Amen.'),
  ('2026-03-17', 'Romans 5:3-4', 'Perseverance builds character, and character produces hope.', 'God, use my trials to grow hope in me. Amen.'),
  ('2026-03-18', 'Psalm 19:14', 'Let the words of my mouth and thoughts of my heart honor You.', 'Lord, guide my words and thoughts today. Amen.'),
  ('2026-03-19', 'Galatians 5:22-23', 'Ask the Spirit to grow love, joy, peace, and patience in you.', 'Holy Spirit, grow Your fruit in me today. Amen.'),
  ('2026-03-20', 'Matthew 7:7', 'Ask, seek, and knock. God delights to answer.', 'Father, I ask and trust You today. Amen.'),
  ('2026-03-21', 'Psalm 46:10', 'Be still and know that God is God.', 'Lord, help me be still and trust You. Amen.'),
  ('2026-03-22', 'Ephesians 4:32', 'Be kind and forgiving as God forgave you.', 'Jesus, make me kind and quick to forgive. Amen.'),
  ('2026-03-23', 'James 1:19', 'Be quick to listen, slow to speak, and slow to anger.', 'Lord, guard my reactions today. Amen.'),
  ('2026-03-24', 'Psalm 100:4', 'Enter Gods presence with thanksgiving and praise.', 'Father, fill me with gratitude today. Amen.'),
  ('2026-03-25', 'Colossians 3:12', 'Clothe yourself with compassion, kindness, and patience.', 'God, help me wear compassion today. Amen.'),
  ('2026-03-26', 'Isaiah 26:3', 'God keeps those in perfect peace whose minds stay on Him.', 'Lord, keep my mind on You today. Amen.'),
  ('2026-03-27', 'Psalm 91:4', 'God covers you with His wings and gives you refuge.', 'Father, shelter me under Your care today. Amen.'),
  ('2026-03-28', 'Romans 8:31', 'If God is for us, who can be against us.', 'Lord, remind me You are for me today. Amen.'),
  ('2026-03-29', 'Hebrews 10:23', 'Hold fast to hope because God is faithful.', 'Jesus, strengthen my hope today. Amen.'),
  ('2026-03-30', 'John 16:33', 'Jesus has overcome the world. Take heart.', 'Lord, help me take heart today. Amen.'),
  ('2026-03-31', 'Psalm 32:8', 'God will instruct you and teach you in the way to go.', 'Father, instruct me today. Amen.'),
  ('2026-04-01', 'Psalm 118:24', 'This is the day the Lord has made. Rejoice in it.', 'Lord, help me rejoice today. Amen.'),
  ('2026-04-02', 'Philippians 1:6', 'God will finish the good work He started in you.', 'God, complete Your work in me. Amen.'),
  ('2026-04-03', 'Psalm 30:5', 'Joy comes in the morning. Hope is coming.', 'Lord, bring fresh joy today. Amen.'),
  ('2026-04-04', 'Matthew 22:37', 'Love God with all your heart, soul, and mind.', 'Jesus, help me love You fully today. Amen.'),
  ('2026-04-05', 'Psalm 27:14', 'Wait for the Lord and be strong and courageous.', 'Lord, give me patience and courage today. Amen.'),
  ('2026-04-06', 'Romans 12:1', 'Offer yourself to God as a living sacrifice.', 'God, I offer my day to You. Amen.'),
  ('2026-04-07', 'Luke 6:31', 'Do for others what you want them to do for you.', 'Father, help me love others well today. Amen.'),
  ('2026-04-08', 'Psalm 16:11', 'In Gods presence there is fullness of joy.', 'Lord, fill me with Your joy today. Amen.'),
  ('2026-04-09', 'Proverbs 4:23', 'Guard your heart, for it shapes your life.', 'Jesus, guard my heart today. Amen.'),
  ('2026-04-10', 'Isaiah 55:8-9', 'Gods ways are higher than ours. Trust His plan.', 'Father, help me trust Your way today. Amen.'),
  ('2026-04-11', 'Matthew 6:34', 'Do not worry about tomorrow. Today has enough.', 'Lord, help me stay present today. Amen.'),
  ('2026-04-12', 'Psalm 139:14', 'You are wonderfully made by God.', 'God, thank You for how You made me. Amen.'),
  ('2026-04-13', 'John 10:10', 'Jesus came to give life in abundance.', 'Jesus, lead me into abundant life today. Amen.'),
  ('2026-04-14', '2 Corinthians 5:17', 'In Christ you are a new creation.', 'Lord, renew me today. Amen.'),
  ('2026-04-15', 'Micah 7:8', 'When you fall, you can rise again.', 'God, lift me up today. Amen.'),
  ('2026-04-16', 'Psalm 84:11', 'God withholds no good thing from those who walk with Him.', 'Father, help me walk with You today. Amen.'),
  ('2026-04-17', 'Hebrews 13:8', 'Jesus is the same yesterday, today, and forever.', 'Jesus, steady my heart today. Amen.'),
  ('2026-04-18', 'Proverbs 17:22', 'A joyful heart is good medicine.', 'Lord, fill me with joy today. Amen.'),
  ('2026-04-19', 'Ephesians 2:10', 'You are Gods workmanship, created for good works.', 'Father, help me do good today. Amen.'),
  ('2026-04-20', 'Psalm 119:11', 'Hide Gods Word in your heart to stay on His path.', 'Lord, plant Your Word in me today. Amen.'),
  ('2026-04-21', 'Matthew 5:9', 'Blessed are the peacemakers.', 'Jesus, make me a peacemaker today. Amen.'),
  ('2026-04-22', 'Psalm 23:4', 'God is with you in the darkest valley.', 'Lord, walk with me today. Amen.'),
  ('2026-04-23', 'Romans 10:13', 'Everyone who calls on the Lord will be saved.', 'Jesus, I call on Your name today. Amen.'),
  ('2026-04-24', 'James 4:8', 'Draw near to God and He will draw near to you.', 'God, draw me close today. Amen.'),
  ('2026-04-25', 'Psalm 145:18', 'The Lord is near to all who call on Him.', 'Lord, I call on You today. Amen.'),
  ('2026-04-26', '1 Corinthians 10:13', 'God provides a way through temptation.', 'Father, help me choose the right way today. Amen.'),
  ('2026-04-27', 'Psalm 34:8', 'Taste and see that the Lord is good.', 'Lord, help me experience Your goodness today. Amen.'),
  ('2026-04-28', 'Isaiah 12:2', 'God is your salvation and strength.', 'Father, be my strength today. Amen.'),
  ('2026-04-29', 'Romans 8:1', 'There is no condemnation for those in Christ.', 'Jesus, free me from shame today. Amen.'),
  ('2026-04-30', 'Ephesians 6:11', 'Put on the full armor of God.', 'Lord, equip me for today. Amen.'),
  ('2026-05-01', 'Psalm 37:4', 'Delight in the Lord and He will give you the desires of your heart.', 'God, be my delight today. Amen.'),
  ('2026-05-02', 'Matthew 28:20', 'Jesus is with you always.', 'Jesus, thank You for being with me. Amen.'),
  ('2026-05-03', 'Psalm 28:7', 'The Lord is your strength and shield.', 'Lord, be my shield today. Amen.'),
  ('2026-05-04', 'Romans 15:4', 'Scripture gives endurance and encouragement.', 'God, encourage me through Your Word today. Amen.'),
  ('2026-05-05', 'Psalm 1:2-3', 'Delight in Gods Word and you will grow strong.', 'Lord, help me delight in Your Word today. Amen.'),
  ('2026-05-06', 'Proverbs 18:10', 'The name of the Lord is a strong tower.', 'Jesus, I run to You today. Amen.'),
  ('2026-05-07', '1 Peter 1:3', 'God gives a living hope through Jesus.', 'Lord, fill me with living hope today. Amen.'),
  ('2026-05-08', 'Isaiah 30:15', 'In quietness and trust is your strength.', 'Father, teach me to rest and trust. Amen.'),
  ('2026-05-09', 'Psalm 90:12', 'Teach us to number our days with wisdom.', 'God, help me use today wisely. Amen.'),
  ('2026-05-10', 'John 13:34', 'Love one another as Jesus loves you.', 'Jesus, help me love well today. Amen.'),
  ('2026-05-11', 'Psalm 61:2', 'When your heart is overwhelmed, God is your rock.', 'Lord, be my rock today. Amen.'),
  ('2026-05-12', 'Romans 8:38-39', 'Nothing can separate you from Gods love.', 'Father, remind me of Your love today. Amen.'),
  ('2026-05-13', 'Matthew 19:26', 'With God all things are possible.', 'God, strengthen my faith today. Amen.'),
  ('2026-05-14', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep watch over me today. Amen.'),
  ('2026-05-15', 'Colossians 1:13', 'God rescues and brings us into His kingdom.', 'Jesus, keep me close today. Amen.'),
  ('2026-05-16', 'Proverbs 3:7-8', 'Fear the Lord and turn from evil; it brings health.', 'God, lead me to healthy choices today. Amen.'),
  ('2026-05-17', 'Psalm 136:1', 'Give thanks to the Lord, His love endures forever.', 'Lord, thank You for Your steadfast love. Amen.'),
  ('2026-05-18', 'Isaiah 54:10', 'Gods love will not be shaken.', 'Father, anchor me in Your love today. Amen.'),
  ('2026-05-19', 'Philippians 2:3', 'Count others more significant than yourself.', 'Jesus, make me humble today. Amen.'),
  ('2026-05-20', 'Psalm 37:7', 'Be still before the Lord and wait patiently for Him.', 'Lord, help me wait well today. Amen.'),
  ('2026-05-21', 'Hebrews 6:19', 'Hope is an anchor for the soul.', 'God, anchor my soul in hope today. Amen.'),
  ('2026-05-22', 'Matthew 5:6', 'Blessed are those who hunger for righteousness.', 'Lord, grow my hunger for You today. Amen.'),
  ('2026-05-23', 'Psalm 119:28', 'God strengthens you in weakness.', 'Father, strengthen me today. Amen.'),
  ('2026-05-24', 'Romans 12:21', 'Overcome evil with good.', 'God, help me choose good today. Amen.'),
  ('2026-05-25', 'Psalm 19:1', 'Creation declares the glory of God.', 'Lord, help me see Your glory today. Amen.'),
  ('2026-05-26', 'Proverbs 15:1', 'A gentle answer turns away wrath.', 'Jesus, make my words gentle today. Amen.'),
  ('2026-05-27', 'John 3:16', 'God so loved the world that He gave His Son.', 'Father, thank You for Your love. Amen.'),
  ('2026-05-28', 'Psalm 73:26', 'God is the strength of your heart forever.', 'Lord, be my strength today. Amen.'),
  ('2026-05-29', 'Hebrews 12:2', 'Fix your eyes on Jesus.', 'Jesus, keep my eyes on You today. Amen.'),
  ('2026-05-30', 'Philippians 4:13', 'You can do all things through Christ who strengthens you.', 'Jesus, strengthen me today. Amen.'),
  ('2026-05-31', 'Psalm 103:2', 'Do not forget all the benefits of the Lord.', 'Lord, I remember Your goodness today. Amen.'),
  ('2026-06-01', 'Psalm 27:4', 'Seek the Lords presence and let Him steady your heart.', 'Lord, I seek You today. Amen.'),
  ('2026-06-02', 'Proverbs 16:9', 'Your plans matter, but God directs your steps.', 'God, guide my steps today. Amen.'),
  ('2026-06-03', 'Psalm 118:6', 'The Lord is with you. You do not need to fear.', 'Father, help me live without fear today. Amen.'),
  ('2026-06-04', 'John 6:35', 'Jesus is the bread of life. He satisfies the soul.', 'Jesus, satisfy me today. Amen.'),
  ('2026-06-05', 'Psalm 56:3', 'When you are afraid, trust in God.', 'Lord, I trust You with my fears. Amen.'),
  ('2026-06-06', 'Isaiah 12:3', 'Draw joy from Gods salvation today.', 'God, fill me with Your joy. Amen.'),
  ('2026-06-07', 'Matthew 5:14', 'You are the light of the world. Shine with humility.', 'Jesus, help me shine Your light. Amen.'),
  ('2026-06-08', 'Romans 5:8', 'God loved you first. Rest in that love.', 'Father, thank You for loving me first. Amen.'),
  ('2026-06-09', 'Psalm 46:1', 'God is your refuge and strength today.', 'Lord, be my refuge today. Amen.'),
  ('2026-06-10', '2 Corinthians 1:3-4', 'God comforts you so you can comfort others.', 'God, comfort me and use me to help others. Amen.'),
  ('2026-06-11', 'James 1:2-3', 'Trials build perseverance when you trust God.', 'Lord, strengthen my perseverance today. Amen.'),
  ('2026-06-12', 'Psalm 91:11', 'God commands His angels to guard you.', 'Lord, thank You for Your protection today. Amen.'),
  ('2026-06-13', 'Matthew 11:29', 'Jesus is gentle and humble. Learn from Him.', 'Jesus, teach me Your gentleness today. Amen.'),
  ('2026-06-14', 'Romans 12:10', 'Honor one another above yourself.', 'God, help me honor others today. Amen.'),
  ('2026-06-15', 'Psalm 19:1', 'Creation declares Gods glory. Look for it today.', 'Lord, open my eyes to Your glory. Amen.'),
  ('2026-06-16', 'Galatians 6:2', 'Carry each others burdens in love.', 'Jesus, help me carry burdens with compassion. Amen.'),
  ('2026-06-17', 'Proverbs 4:25', 'Fix your eyes straight ahead with purpose.', 'Lord, keep me focused today. Amen.'),
  ('2026-06-18', 'Isaiah 26:4', 'Trust the Lord forever; He is your rock.', 'God, I trust You today. Amen.'),
  ('2026-06-19', 'Psalm 112:7', 'Do not fear bad news; trust in the Lord.', 'Father, steady my heart with Your peace. Amen.'),
  ('2026-06-20', 'John 15:9', 'Abide in Jesus love and stay close.', 'Jesus, keep me close to You today. Amen.'),
  ('2026-06-21', 'Psalm 136:26', 'Give thanks for Gods faithful love.', 'Lord, thank You for Your faithful love. Amen.'),
  ('2026-06-22', 'Romans 8:26', 'The Spirit helps you when you do not know how to pray.', 'Holy Spirit, help me pray today. Amen.'),
  ('2026-06-23', 'Proverbs 3:3-4', 'Hold tight to love and faithfulness.', 'God, make me loving and faithful today. Amen.'),
  ('2026-06-24', 'Psalm 121:5', 'The Lord watches over you.', 'Lord, keep watch over me today. Amen.'),
  ('2026-06-25', 'Philippians 2:14', 'Do everything without complaining.', 'Jesus, help me choose gratitude today. Amen.'),
  ('2026-06-26', 'Matthew 6:6', 'Meet with God in the quiet.', 'Father, draw me into quiet with You. Amen.'),
  ('2026-06-27', 'Psalm 62:5', 'Find rest in God alone.', 'Lord, give me rest today. Amen.'),
  ('2026-06-28', 'Romans 14:8', 'Whether you live or die, you belong to the Lord.', 'Jesus, I belong to You. Amen.'),
  ('2026-06-29', 'Psalm 40:1', 'God hears when you cry and lifts you up.', 'Lord, thank You for hearing me. Amen.'),
  ('2026-06-30', 'Ephesians 3:20', 'God can do more than you ask or imagine.', 'God, expand my faith today. Amen.'),
  ('2026-07-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-07-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-07-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-07-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-07-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-07-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-07-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-07-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-07-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-07-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-07-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-07-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-07-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-07-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-07-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-07-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-07-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-07-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-07-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-07-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-07-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-07-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-07-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-07-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-07-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-07-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-07-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-07-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-07-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-07-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-07-31', 'Galatians 5:1', 'Stand firm in the freedom Christ gives.', 'Jesus, keep me free and steady. Amen.'),
  ('2026-08-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-08-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-08-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-08-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-08-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-08-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-08-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-08-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-08-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-08-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-08-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-08-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-08-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-08-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-08-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-08-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-08-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-08-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-08-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-08-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-08-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-08-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-08-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-08-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-08-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-08-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-08-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-08-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-08-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-08-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-08-31', 'Galatians 5:1', 'Stand firm in the freedom Christ gives.', 'Jesus, keep me free and steady. Amen.'),
  ('2026-09-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-09-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-09-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-09-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-09-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-09-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-09-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-09-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-09-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-09-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-09-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-09-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-09-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-09-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-09-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-09-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-09-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-09-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-09-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-09-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-09-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-09-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-09-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-09-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-09-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-09-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-09-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-09-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-09-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-09-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-10-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-10-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-10-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-10-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-10-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-10-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-10-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-10-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-10-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-10-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-10-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-10-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-10-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-10-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-10-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-10-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-10-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-10-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-10-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-10-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-10-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-10-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-10-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-10-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-10-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-10-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-10-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-10-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-10-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-10-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-10-31', 'Galatians 5:1', 'Stand firm in the freedom Christ gives.', 'Jesus, keep me free and steady. Amen.'),
  ('2026-11-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-11-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-11-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-11-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-11-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-11-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-11-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-11-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-11-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-11-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-11-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-11-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-11-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-11-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-11-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-11-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-11-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-11-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-11-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-11-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-11-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-11-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-11-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-11-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-11-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-11-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-11-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-11-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-11-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-11-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-12-01', 'Psalm 90:17', 'Let Gods favor rest on your work today.', 'Lord, establish the work of my hands. Amen.'),
  ('2026-12-02', 'Lamentations 3:25', 'God is good to those who seek Him.', 'Father, I seek You today. Amen.'),
  ('2026-12-03', 'Proverbs 3:5-6', 'Trust God with your whole heart today.', 'Lord, guide my path today. Amen.'),
  ('2026-12-04', 'Isaiah 41:13', 'God holds your hand and helps you.', 'God, hold me steady today. Amen.'),
  ('2026-12-05', 'Psalm 34:4', 'God hears you and delivers you from fear.', 'Lord, free me from fear today. Amen.'),
  ('2026-12-06', 'Matthew 5:8', 'A pure heart sees God clearly.', 'Jesus, cleanse my heart today. Amen.'),
  ('2026-12-07', 'Romans 12:2', 'Let God renew your mind today.', 'Lord, renew my mind today. Amen.'),
  ('2026-12-08', 'Psalm 37:23', 'God orders your steps.', 'Father, direct my steps today. Amen.'),
  ('2026-12-09', 'Philippians 4:19', 'God will supply what you need.', 'Lord, provide for me today. Amen.'),
  ('2026-12-10', 'James 1:17', 'Every good gift comes from God.', 'Father, thank You for Your gifts. Amen.'),
  ('2026-12-11', 'Psalm 46:1', 'God is your refuge and strength.', 'Lord, be my refuge today. Amen.'),
  ('2026-12-12', 'Isaiah 40:29', 'God gives strength to the weary.', 'Father, strengthen me today. Amen.'),
  ('2026-12-13', '1 John 4:18', 'Perfect love drives out fear.', 'Jesus, fill me with Your love. Amen.'),
  ('2026-12-14', 'Colossians 3:15', 'Let the peace of Christ rule your heart.', 'Lord, fill me with Your peace. Amen.'),
  ('2026-12-15', 'Psalm 16:8', 'God is at your right hand.', 'Father, keep me steady today. Amen.'),
  ('2026-12-16', 'John 14:6', 'Jesus is the way, the truth, and the life.', 'Jesus, lead me in Your truth today. Amen.'),
  ('2026-12-17', 'Hebrews 13:5', 'God will never leave you.', 'Lord, thank You for staying close. Amen.'),
  ('2026-12-18', 'Psalm 119:105', 'Gods Word lights your path.', 'Lord, guide me by Your Word today. Amen.'),
  ('2026-12-19', '1 Peter 2:9', 'You are chosen and called.', 'God, help me walk in my calling. Amen.'),
  ('2026-12-20', 'Romans 8:28', 'God works all things for good.', 'Lord, help me trust Your plan. Amen.'),
  ('2026-12-21', 'Psalm 63:1', 'Seek God early and earnestly.', 'Father, I seek You today. Amen.'),
  ('2026-12-22', 'Matthew 6:9-13', 'Pray with confidence to your Father.', 'God, teach me to pray today. Amen.'),
  ('2026-12-23', 'Isaiah 30:21', 'God will guide you in the way to go.', 'Lord, guide me clearly today. Amen.'),
  ('2026-12-24', 'Psalm 27:1', 'The Lord is your light and salvation.', 'Jesus, be my light today. Amen.'),
  ('2026-12-25', '2 Corinthians 5:7', 'Walk by faith, not by sight.', 'Lord, help me walk by faith today. Amen.'),
  ('2026-12-26', 'Philippians 2:13', 'God works in you to will and act.', 'God, work through me today. Amen.'),
  ('2026-12-27', 'Psalm 121:7-8', 'The Lord watches over your life.', 'Lord, keep me safe today. Amen.'),
  ('2026-12-28', 'James 1:12', 'Persevere and receive the crown of life.', 'Father, help me persevere today. Amen.'),
  ('2026-12-29', 'Romans 15:13', 'God fills you with joy and peace.', 'Lord, fill me with joy today. Amen.'),
  ('2026-12-30', 'Psalm 118:24', 'Rejoice in the day God has made.', 'God, help me rejoice today. Amen.'),
  ('2026-12-31', 'Galatians 5:1', 'Stand firm in the freedom Christ gives.', 'Jesus, keep me free and steady. Amen.');
