begin;

create table if not exists public.plan_suggestions (
  id bigint generated by default as identity primary key,
  phrase text not null check (char_length(phrase) >= 4 and char_length(phrase) <= 200),
  created_at timestamptz not null default now()
);

alter table public.plan_suggestions enable row level security;

drop policy if exists "plan_suggestions_insert_anon" on public.plan_suggestions;
create policy "plan_suggestions_insert_anon"
  on public.plan_suggestions
  for insert
  to anon, authenticated
  with check (char_length(phrase) >= 4 and char_length(phrase) <= 200);

revoke all on public.plan_suggestions from public;
grant insert on public.plan_suggestions to anon;
grant insert on public.plan_suggestions to authenticated;

create index if not exists plan_suggestions_created_at_idx on public.plan_suggestions(created_at desc);

comment on table public.plan_suggestions is 'Anonymous Battle Plan topic suggestions. Anon INSERT only.';

commit;
